# Copyright 2023-2025 Kinetic Commerce and contributors
#
# Derived from tisonkun/actions-dco, copyright 2021 tison <wander4096@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this
# file except in compliance with the License. You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under
# the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied. See the License for the specific language governing
# permissions and limitations under the License.

name: 'Enforce DCO Sign-off'
description: |
  Enforce Developer Certificate of Origin (DCO) sign-off on Pull Requests
author: 'KineticCafe'
inputs:
  repo-token:
    description: 'The GitHub token'
    required: false
    default: ${{ github.token }}
  exempt-authors:
    description: |
      A whitespace separated list of email exemption patterns indicating an implied DCO
      sign-off (the contributors work for the company managing the project, for example).
      Permitted pattern formats are exact emails (`name@example.org`) or domain patterns
      (`@example.org`). Patterns that do not match this will be printed as warnings and
      ignored.

      `exempt-authors` are applied only for the commit _author_. The commit _committer_
      cannot exempt other peoples' contributions.

runs:
  using: 'node24'
  main: 'dist/index.js'

branding:
  icon: check-circle
  color: blue
