name = "dco_check"
version = "3.0.0"
target = "javascript"

description = "Enforce Developer Certificate of Origin (DCO) sign-off on Pull Requests"
licences = ["Apache-2.0"]
repository = { type = "github", user = "KineticCafe", repo = "actions_dco" }

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_json = ">= 3.0.0 and < 4.0.0"
gleam_fetch = ">= 1.3.0 and < 2.0.0"
tom = ">= 2.0.0 and < 3.0.0"
glemplate = ">= 8.0.0 and < 9.0.0"
shellout = ">= 1.8.0 and < 2.0.0"
filepath = ">= 1.0.0 and < 2.0.0"
gleam_javascript = ">= 1.0.0 and < 2.0.0"
envoy = ">= 1.1.0 and < 2.0.0"
clip = ">= 1.2.0 and < 2.0.0"
pontil = ">= 1.0.0 and < 2.0.0"
gleam_http = ">= 4.3.0 and < 5.0.0"
simplifile = ">= 2.4.0 and < 3.0.0"
gleam_regexp = ">= 1.1.1 and < 2.0.0"
capuchin_crypt = ">= 1.0.0 and < 2.0.0"
pontil_summary = ">= 1.0.0 and < 2.0.0"
pontil_context = ">= 1.0.0 and < 2.0.0"
houdini = ">= 1.2.1 and < 2.0.0"
oaspec = ">= 0.17.0 and < 1.0.0"
oaspec_fetch = ">= 0.1.0 and < 1.0.0"
glint = ">= 1.2.1 and < 2.0.0"
argv = ">= 1.0.2 and < 2.0.0"
pontil_core = ">= 1.0.0 and < 2.0.0"

[dev_dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
qcheck = ">= 1.0.4 and < 2.0.0"
gilly = ">= 0.3.1 and < 1.0.0"
pontil_build = ">= 1.0.0 and < 2.0.0"
glinter = ">= 2.16.0 and < 3.0.0"
take = ">= 1.0.0 and < 2.0.0"

[tools.glinter]
stats = true

[tools.glinter.rules]
unused_exports = "off"
ffi_usage = "error"
function_complexity = "warning"
module_complexity = "warning"

[tools.glinter.ignore]
"src/dco_check/internal/github/*.gleam" = [
  "thrown_away_error",
  "function_complexity",
  "missing_labels",
]

[tools.pontil_build.bundle]
entry = "dco_check_action.gleam"
