// Code generated by oaspec v0.69.0. DO NOT EDIT.

import dco_check/internal/github/decode
import dco_check/internal/github/encode
import dco_check/internal/github/request_types
import dco_check/internal/github/response_types
import dco_check/internal/github/types
import gleam/dynamic/decode as dyn_decode
import gleam/int
import gleam/json
import gleam/list
import gleam/option.{type Option, None, Some}
import gleam/result
import gleam/string
import gleam/uri
import oaspec/transport

/// HTTP client errors.
pub type ClientError {
  TransportError(error: transport.TransportError)
  DecodeFailure(detail: String)
  InvalidResponse(detail: String)
  UnexpectedStatus(
    status: Int,
    headers: List(#(String, String)),
    body: transport.Body,
  )
}

/// Default base URL declared by the OpenAPI spec.
pub fn default_base_url() -> String {
  "https://api.github.com"
}

fn text_body(body: transport.Body) -> Result(String, ClientError) {
  case body {
    transport.TextBody(text) -> Ok(text)
    transport.BytesBody(_) ->
      Error(InvalidResponse(detail: "expected text body, got bytes"))
    transport.EmptyBody ->
      Error(InvalidResponse(detail: "expected text body, got empty body"))
  }
}

// fn bytes_body(body: transport.Body) -> Result(BitArray, ClientError) {
//   case body {
//     transport.BytesBody(bytes) -> Ok(bytes)
//     transport.TextBody(_) ->
//       Error(InvalidResponse(detail: "expected binary body, got text"))
//     transport.EmptyBody ->
//       Error(InvalidResponse(detail: "expected binary body, got empty body"))
//   }
// }

fn await_response(
  response_async: transport.Async(
    Result(transport.Response, transport.TransportError),
  ),
  decode: fn(transport.Response) -> Result(a, ClientError),
) -> transport.Async(Result(a, ClientError)) {
  response_async
  |> transport.map(fn(resp_result) {
    resp_result |> result.map_error(TransportError)
  })
  |> transport.map_try(decode)
}

/// Compare two commits
/// Compares two commits against one another. You can compare refs (branches or tags) and commit SHAs in the same repository, or you can compare refs and commit SHAs that exist in different repositories within the same repository network, including fork branches. For more information about how to view a repository's network, see "[Understanding connections between repositories](https://docs.github.com/repositories/viewing-activity-and-data-for-your-repository/understanding-connections-between-repositories)."
///
/// This endpoint is equivalent to running the `git log BASE..HEAD` command, but it returns commits in a different order. The `git log BASE..HEAD` command returns commits in reverse chronological order, whereas the API returns commits in chronological order.
///
/// This endpoint supports the following custom media types. For more information, see "[Media types](https://docs.github.com/rest/using-the-rest-api/getting-started-with-the-rest-api#media-types)."
///
/// - **`application/vnd.github.diff`**: Returns the diff of the commit.
/// - **`application/vnd.github.patch`**: Returns the patch of the commit. Diffs with binary data will have no `patch` property.
///
/// The API response includes details about the files that were changed between the two commits. This includes the status of the change (if a file was added, removed, modified, or renamed), and details of the change itself. For example, files with a `renamed` status have a `previous_filename` field showing the previous filename of the file, and files with a `modified` status have a `patch` field showing the changes made to the file.
///
/// When calling this endpoint without any paging parameter (`per_page` or `page`), the returned list is limited to 250 commits, and the last commit in the list is the most recent of the entire comparison.
///
/// **Working with large comparisons**
///
/// To process a response with a large number of commits, use a query parameter (`per_page` or `page`) to paginate the results. When using pagination:
///
/// - The list of changed files is only shown on the first page of results, and it includes up to 300 changed files for the entire comparison.
/// - The results are returned in chronological order, but the last commit in the returned list may not be the most recent one in the entire set if there are more pages of results.
///
/// For more information on working with pagination, see "[Using pagination in the REST API](https://docs.github.com/rest/guides/using-pagination-in-the-rest-api)."
///
/// **Signature verification object**
///
/// The response will include a `verification` object that describes the result of verifying the commit's signature. The `verification` object includes the following fields:
///
/// | Name | Type | Description |
/// | ---- | ---- | ----------- |
/// | `verified` | `boolean` | Indicates whether GitHub considers the signature in this commit to be verified. |
/// | `reason` | `string` | The reason for verified value. Possible values and their meanings are enumerated in table below. |
/// | `signature` | `string` | The signature that was extracted from the commit. |
/// | `payload` | `string` | The value that was signed. |
/// | `verified_at` | `string` | The date the signature was verified by GitHub. |
///
/// These are the possible values for `reason` in the `verification` object:
///
/// | Value | Description |
/// | ----- | ----------- |
/// | `expired_key` | The key that made the signature is expired. |
/// | `not_signing_key` | The "signing" flag is not among the usage flags in the GPG key that made the signature. |
/// | `gpgverify_error` | There was an error communicating with the signature verification service. |
/// | `gpgverify_unavailable` | The signature verification service is currently unavailable. |
/// | `unsigned` | The object does not include a signature. |
/// | `unknown_signature_type` | A non-PGP signature was found in the commit. |
/// | `no_user` | No user was associated with the `committer` email address in the commit. |
/// | `unverified_email` | The `committer` email address in the commit was associated with a user, but the email address is not verified on their account. |
/// | `bad_email` | The `committer` email address in the commit is not included in the identities of the PGP key that made the signature. |
/// | `unknown_key` | The key that made the signature has not been registered with any user's account. |
/// | `malformed_signature` | There was an error parsing the signature. |
/// | `invalid` | The signature could not be cryptographically verified using the key whose key-id was found in the signature. |
/// | `valid` | None of the above errors applied, so the signature is considered to be verified. |
pub fn repos_compare_commits(
  send send: transport.Send,
  owner owner: String,
  repo repo: String,
  basehead basehead: String,
  page page: Option(Int),
  per_page per_page: Option(Int),
) -> Result(response_types.ReposCompareCommitsResponse, ClientError) {
  use req <- result.try(build_repos_compare_commits_request(
    owner: owner,
    repo: repo,
    basehead: basehead,
    page: page,
    per_page: per_page,
  ))
  use resp <- result.try(
    send(req)
    |> result.map_error(TransportError),
  )
  decode_repos_compare_commits_response(resp)
}

/// Async transport variant of repos_compare_commits. Resolves to the typed response or a client error.
pub fn repos_compare_commits_async(
  async_send async_send: transport.AsyncSend,
  owner owner: String,
  repo repo: String,
  basehead basehead: String,
  page page: Option(Int),
  per_page per_page: Option(Int),
) -> transport.Async(
  Result(response_types.ReposCompareCommitsResponse, ClientError),
) {
  case
    build_repos_compare_commits_request(
      owner: owner,
      repo: repo,
      basehead: basehead,
      page: page,
      per_page: per_page,
    )
  {
    Ok(req) ->
      await_response(async_send(req), decode_repos_compare_commits_response)
    Error(error) -> transport.resolve(Error(error))
  }
}

/// Build the transport request for repos_compare_commits without sending it. Useful for testing and for adding custom transport middleware.
pub fn build_repos_compare_commits_request(
  owner owner: String,
  repo repo: String,
  basehead basehead: String,
  page page: Option(Int),
  per_page per_page: Option(Int),
) -> Result(transport.Request, ClientError) {
  let path = "/repos/{owner}/{repo}/compare/{basehead}"
  let path = string.replace(path, "{owner}", uri.percent_encode(owner))
  let path = string.replace(path, "{repo}", uri.percent_encode(repo))
  let path = string.replace(path, "{basehead}", uri.percent_encode(basehead))
  let query = []
  let query = case page {
    Some(v) -> [#("page", int.to_string(v)), ..query]
    None -> query
  }
  let query = case per_page {
    Some(v) -> [#("per_page", int.to_string(v)), ..query]
    None -> query
  }
  let query = list.reverse(query)
  let headers = []
  let body = transport.EmptyBody
  Ok(
    transport.Request(
      method: transport.Get,
      base_url: Some(default_base_url()),
      path: path,
      query: query,
      headers: headers,
      body: body,
      security: [],
    ),
  )
}

/// Decode a transport response into the typed response variant for repos_compare_commits.
pub fn decode_repos_compare_commits_response(
  resp: transport.Response,
) -> Result(response_types.ReposCompareCommitsResponse, ClientError) {
  case resp.status {
    200 -> {
      use text <- result.try(text_body(resp.body))
      Ok(response_types.ReposCompareCommitsResponseOk(text))
    }
    404 -> {
      use text <- result.try(text_body(resp.body))
      case decode.decode_basic_error(text) {
        Ok(decoded) ->
          Ok(response_types.ReposCompareCommitsResponseNotFound(decoded))
        Error(_) ->
          Error(DecodeFailure(detail: "Failed to decode response body"))
      }
    }
    500 -> {
      use text <- result.try(text_body(resp.body))
      case decode.decode_basic_error(text) {
        Ok(decoded) ->
          Ok(response_types.ReposCompareCommitsResponseInternalServerError(
            decoded,
          ))
        Error(_) ->
          Error(DecodeFailure(detail: "Failed to decode response body"))
      }
    }
    503 -> {
      use text <- result.try(text_body(resp.body))
      case
        decode.decode_repos_compare_commits_response_service_unavailable(text)
      {
        Ok(decoded) ->
          Ok(response_types.ReposCompareCommitsResponseServiceUnavailable(
            decoded,
          ))
        Error(_) ->
          Error(DecodeFailure(detail: "Failed to decode response body"))
      }
    }
    _ ->
      Error(UnexpectedStatus(
        status: resp.status,
        headers: resp.headers,
        body: resp.body,
      ))
  }
}

/// Request-object wrapper. Delegates to repos_compare_commits with fields unpacked from the request record.
pub fn repos_compare_commits_with_request(
  send send: transport.Send,
  request request: request_types.ReposCompareCommitsRequest,
) -> Result(response_types.ReposCompareCommitsResponse, ClientError) {
  repos_compare_commits(
    send,
    request.owner,
    request.repo,
    request.basehead,
    request.page,
    request.per_page,
  )
}

/// Async request-object wrapper. Delegates to repos_compare_commits_async with fields unpacked from the request record.
pub fn repos_compare_commits_with_request_async(
  async_send async_send: transport.AsyncSend,
  request request: request_types.ReposCompareCommitsRequest,
) -> transport.Async(
  Result(response_types.ReposCompareCommitsResponse, ClientError),
) {
  repos_compare_commits_async(
    async_send,
    request.owner,
    request.repo,
    request.basehead,
    request.page,
    request.per_page,
  )
}

/// Get repository content
/// Gets the contents of a file or directory in a repository. Specify the file path or directory with the `path` parameter. If you omit the `path` parameter, you will receive the contents of the repository's root directory.
///
/// This endpoint supports the following custom media types. For more information, see "[Media types](https://docs.github.com/rest/using-the-rest-api/getting-started-with-the-rest-api#media-types)."
///
/// - **`application/vnd.github.raw+json`**: Returns the raw file contents for files and symlinks.
/// - **`application/vnd.github.html+json`**: Returns the file contents in HTML. Markup languages are rendered to HTML using GitHub's open-source [Markup library](https://github.com/github/markup).
/// - **`application/vnd.github.object+json`**: Returns the contents in a consistent object format regardless of the content type. For example, instead of an array of objects for a directory, the response will be an object with an `entries` attribute containing the array of objects.
///
/// If the content is a directory, the response will be an array of objects, one object for each item in the directory. When listing the contents of a directory, submodules have their "type" specified as "file". Logically, the value _should_ be "submodule". This behavior exists [for backwards compatibility purposes](https://git.io/v1YCW). In the next major version of the API, the type will be returned as "submodule".
///
/// If the content is a symlink and the symlink's target is a normal file in the repository, then the API responds with the content of the file. Otherwise, the API responds with an object describing the symlink itself.
///
/// If the content is a submodule, the `submodule_git_url` field identifies the location of the submodule repository, and the `sha` identifies a specific commit within the submodule repository. Git uses the given URL when cloning the submodule repository, and checks out the submodule at that specific commit. If the submodule repository is not hosted on github.com, the Git URLs (`git_url` and `_links["git"]`) and the github.com URLs (`html_url` and `_links["html"]`) will have null values.
///
/// **Notes**:
///
/// - To get a repository's contents recursively, you can [recursively get the tree](https://docs.github.com/rest/git/trees#get-a-tree).
/// - This API has an upper limit of 1,000 files for a directory. If you need to retrieve
/// more files, use the [Git Trees API](https://docs.github.com/rest/git/trees#get-a-tree).
/// - Download URLs expire and are meant to be used just once. To ensure the download URL does not expire, please use the contents API to obtain a fresh download URL for each download.
/// - If the requested file's size is:
///   - 1 MB or smaller: All features of this endpoint are supported.
///   - Between 1-100 MB: Only the `raw` or `object` custom media types are supported. Both will work as normal, except that when using the `object` media type, the `content` field will be an empty
/// string and the `encoding` field will be `"none"`. To get the contents of these larger files, use the `raw` media type.
///   - Greater than 100 MB: This endpoint is not supported.
pub fn repos_get_content(
  send send: transport.Send,
  owner owner: String,
  repo repo: String,
  path_2 path_2: String,
  ref ref: Option(String),
  body body: Option(String),
) -> Result(response_types.ReposGetContentResponse, ClientError) {
  use req <- result.try(build_repos_get_content_request(
    owner: owner,
    repo: repo,
    path_2: path_2,
    ref: ref,
    body: body,
  ))
  use resp <- result.try(
    send(req)
    |> result.map_error(TransportError),
  )
  decode_repos_get_content_response(resp)
}

/// Async transport variant of repos_get_content. Resolves to the typed response or a client error.
pub fn repos_get_content_async(
  async_send async_send: transport.AsyncSend,
  owner owner: String,
  repo repo: String,
  path_2 path_2: String,
  ref ref: Option(String),
  body body: Option(String),
) -> transport.Async(
  Result(response_types.ReposGetContentResponse, ClientError),
) {
  case
    build_repos_get_content_request(
      owner: owner,
      repo: repo,
      path_2: path_2,
      ref: ref,
      body: body,
    )
  {
    Ok(req) ->
      await_response(async_send(req), decode_repos_get_content_response)
    Error(error) -> transport.resolve(Error(error))
  }
}

/// Build the transport request for repos_get_content without sending it. Useful for testing and for adding custom transport middleware.
pub fn build_repos_get_content_request(
  owner owner: String,
  repo repo: String,
  path_2 path_2: String,
  ref ref: Option(String),
  body body: Option(String),
) -> Result(transport.Request, ClientError) {
  let path = "/repos/{owner}/{repo}/contents/{path}"
  let path = string.replace(path, "{owner}", uri.percent_encode(owner))
  let path = string.replace(path, "{repo}", uri.percent_encode(repo))
  let path = string.replace(path, "{path}", uri.percent_encode(path_2))
  let query = []
  let query = case ref {
    Some(v) -> [#("ref", v), ..query]
    None -> query
  }
  let query = list.reverse(query)
  let headers = []
  let body = case body {
    Some(body) -> transport.TextBody(body)
    None -> transport.EmptyBody
  }
  let headers = case body {
    transport.EmptyBody -> headers
    _ -> [#("content-type", "application/json"), ..headers]
  }
  Ok(
    transport.Request(
      method: transport.Get,
      base_url: Some(default_base_url()),
      path: path,
      query: query,
      headers: headers,
      body: body,
      security: [],
    ),
  )
}

/// Decode a transport response into the typed response variant for repos_get_content.
pub fn decode_repos_get_content_response(
  resp: transport.Response,
) -> Result(response_types.ReposGetContentResponse, ClientError) {
  case resp.status {
    200 -> {
      use text <- result.try(text_body(resp.body))
      Ok(response_types.ReposGetContentResponseOk(text))
    }
    302 -> Ok(response_types.ReposGetContentResponseFound)
    304 -> Ok(response_types.ReposGetContentResponseNotModified)
    403 -> {
      use text <- result.try(text_body(resp.body))
      case decode.decode_basic_error(text) {
        Ok(decoded) ->
          Ok(response_types.ReposGetContentResponseForbidden(decoded))
        Error(_) ->
          Error(DecodeFailure(detail: "Failed to decode response body"))
      }
    }
    404 -> {
      use text <- result.try(text_body(resp.body))
      case decode.decode_basic_error(text) {
        Ok(decoded) ->
          Ok(response_types.ReposGetContentResponseNotFound(decoded))
        Error(_) ->
          Error(DecodeFailure(detail: "Failed to decode response body"))
      }
    }
    _ ->
      Error(UnexpectedStatus(
        status: resp.status,
        headers: resp.headers,
        body: resp.body,
      ))
  }
}

/// Request-object wrapper. Delegates to repos_get_content with fields unpacked from the request record.
pub fn repos_get_content_with_request(
  send send: transport.Send,
  request request: request_types.ReposGetContentRequest,
) -> Result(response_types.ReposGetContentResponse, ClientError) {
  repos_get_content(
    send,
    request.owner,
    request.repo,
    request.path_2,
    request.ref,
    request.body,
  )
}

/// Async request-object wrapper. Delegates to repos_get_content_async with fields unpacked from the request record.
pub fn repos_get_content_with_request_async(
  async_send async_send: transport.AsyncSend,
  request request: request_types.ReposGetContentRequest,
) -> transport.Async(
  Result(response_types.ReposGetContentResponse, ClientError),
) {
  repos_get_content_async(
    async_send,
    request.owner,
    request.repo,
    request.path_2,
    request.ref,
    request.body,
  )
}

/// Create or update file contents
/// Creates a new file or replaces an existing file in a repository.
///
/// > [!NOTE]
/// > If you use this endpoint and the "[Delete a file](https://docs.github.com/rest/repos/contents/#delete-a-file)" endpoint in parallel, the concurrent requests will conflict and you will receive errors. You must use these endpoints serially instead.
///
/// OAuth app tokens and personal access tokens (classic) need the `repo` scope to use this endpoint. The `workflow` scope is also required in order to modify files in the `.github/workflows` directory.
pub fn repos_create_or_update_file_contents(
  send send: transport.Send,
  owner owner: String,
  repo repo: String,
  path_2 path_2: String,
  body body: types.ReposCreateOrUpdateFileContentsRequest,
) -> Result(response_types.ReposCreateOrUpdateFileContentsResponse, ClientError) {
  use req <- result.try(build_repos_create_or_update_file_contents_request(
    owner: owner,
    repo: repo,
    path_2: path_2,
    body: body,
  ))
  use resp <- result.try(
    send(req)
    |> result.map_error(TransportError),
  )
  decode_repos_create_or_update_file_contents_response(resp)
}

/// Async transport variant of repos_create_or_update_file_contents. Resolves to the typed response or a client error.
pub fn repos_create_or_update_file_contents_async(
  async_send async_send: transport.AsyncSend,
  owner owner: String,
  repo repo: String,
  path_2 path_2: String,
  body body: types.ReposCreateOrUpdateFileContentsRequest,
) -> transport.Async(
  Result(response_types.ReposCreateOrUpdateFileContentsResponse, ClientError),
) {
  case
    build_repos_create_or_update_file_contents_request(
      owner: owner,
      repo: repo,
      path_2: path_2,
      body: body,
    )
  {
    Ok(req) ->
      await_response(
        async_send(req),
        decode_repos_create_or_update_file_contents_response,
      )
    Error(error) -> transport.resolve(Error(error))
  }
}

/// Build the transport request for repos_create_or_update_file_contents without sending it. Useful for testing and for adding custom transport middleware.
pub fn build_repos_create_or_update_file_contents_request(
  owner owner: String,
  repo repo: String,
  path_2 path_2: String,
  body body: types.ReposCreateOrUpdateFileContentsRequest,
) -> Result(transport.Request, ClientError) {
  let path = "/repos/{owner}/{repo}/contents/{path}"
  let path = string.replace(path, "{owner}", uri.percent_encode(owner))
  let path = string.replace(path, "{repo}", uri.percent_encode(repo))
  let path = string.replace(path, "{path}", uri.percent_encode(path_2))
  let query = []
  let headers = []
  let body =
    transport.TextBody(
      encode.encode_repos_create_or_update_file_contents_request(body),
    )
  let headers = [#("content-type", "application/json"), ..headers]
  Ok(
    transport.Request(
      method: transport.Put,
      base_url: Some(default_base_url()),
      path: path,
      query: query,
      headers: headers,
      body: body,
      security: [],
    ),
  )
}

/// Decode a transport response into the typed response variant for repos_create_or_update_file_contents.
pub fn decode_repos_create_or_update_file_contents_response(
  resp: transport.Response,
) -> Result(response_types.ReposCreateOrUpdateFileContentsResponse, ClientError) {
  case resp.status {
    200 -> {
      use text <- result.try(text_body(resp.body))
      case decode.decode_file_commit(text) {
        Ok(decoded) ->
          Ok(response_types.ReposCreateOrUpdateFileContentsResponseOk(decoded))
        Error(_) ->
          Error(DecodeFailure(detail: "Failed to decode response body"))
      }
    }
    201 -> {
      use text <- result.try(text_body(resp.body))
      case decode.decode_file_commit(text) {
        Ok(decoded) ->
          Ok(response_types.ReposCreateOrUpdateFileContentsResponseCreated(
            decoded,
          ))
        Error(_) ->
          Error(DecodeFailure(detail: "Failed to decode response body"))
      }
    }
    404 -> {
      use text <- result.try(text_body(resp.body))
      case decode.decode_basic_error(text) {
        Ok(decoded) ->
          Ok(response_types.ReposCreateOrUpdateFileContentsResponseNotFound(
            decoded,
          ))
        Error(_) ->
          Error(DecodeFailure(detail: "Failed to decode response body"))
      }
    }
    409 -> {
      use text <- result.try(text_body(resp.body))
      case
        decode.decode_repos_create_or_update_file_contents_response_conflict(
          text,
        )
      {
        Ok(decoded) ->
          Ok(response_types.ReposCreateOrUpdateFileContentsResponseConflict(
            decoded,
          ))
        Error(_) ->
          Error(DecodeFailure(detail: "Failed to decode response body"))
      }
    }
    422 -> {
      use text <- result.try(text_body(resp.body))
      case decode.decode_validation_error(text) {
        Ok(decoded) ->
          Ok(
            response_types.ReposCreateOrUpdateFileContentsResponseUnprocessableEntity(
              decoded,
            ),
          )
        Error(_) ->
          Error(DecodeFailure(detail: "Failed to decode response body"))
      }
    }
    _ ->
      Error(UnexpectedStatus(
        status: resp.status,
        headers: resp.headers,
        body: resp.body,
      ))
  }
}

/// Request-object wrapper. Delegates to repos_create_or_update_file_contents with fields unpacked from the request record.
pub fn repos_create_or_update_file_contents_with_request(
  send send: transport.Send,
  request request: request_types.ReposCreateOrUpdateFileContentsRequest,
) -> Result(response_types.ReposCreateOrUpdateFileContentsResponse, ClientError) {
  repos_create_or_update_file_contents(
    send,
    request.owner,
    request.repo,
    request.path_2,
    request.body,
  )
}

/// Async request-object wrapper. Delegates to repos_create_or_update_file_contents_async with fields unpacked from the request record.
pub fn repos_create_or_update_file_contents_with_request_async(
  async_send async_send: transport.AsyncSend,
  request request: request_types.ReposCreateOrUpdateFileContentsRequest,
) -> transport.Async(
  Result(response_types.ReposCreateOrUpdateFileContentsResponse, ClientError),
) {
  repos_create_or_update_file_contents_async(
    async_send,
    request.owner,
    request.repo,
    request.path_2,
    request.body,
  )
}

/// Delete a file
/// Deletes a file in a repository.
///
/// You can provide an additional `committer` parameter, which is an object containing information about the committer. Or, you can provide an `author` parameter, which is an object containing information about the author.
///
/// The `author` section is optional and is filled in with the `committer` information if omitted. If the `committer` information is omitted, the authenticated user's information is used.
///
/// You must provide values for both `name` and `email`, whether you choose to use `author` or `committer`. Otherwise, you'll receive a `422` status code.
///
/// > [!NOTE]
/// > If you use this endpoint and the "[Create or update file contents](https://docs.github.com/rest/repos/contents/#create-or-update-file-contents)" endpoint in parallel, the concurrent requests will conflict and you will receive errors. You must use these endpoints serially instead.
pub fn repos_delete_file(
  send send: transport.Send,
  owner owner: String,
  repo repo: String,
  path_2 path_2: String,
  body body: types.ReposDeleteFileRequest,
) -> Result(response_types.ReposDeleteFileResponse, ClientError) {
  use req <- result.try(build_repos_delete_file_request(
    owner: owner,
    repo: repo,
    path_2: path_2,
    body: body,
  ))
  use resp <- result.try(
    send(req)
    |> result.map_error(TransportError),
  )
  decode_repos_delete_file_response(resp)
}

/// Async transport variant of repos_delete_file. Resolves to the typed response or a client error.
pub fn repos_delete_file_async(
  async_send async_send: transport.AsyncSend,
  owner owner: String,
  repo repo: String,
  path_2 path_2: String,
  body body: types.ReposDeleteFileRequest,
) -> transport.Async(
  Result(response_types.ReposDeleteFileResponse, ClientError),
) {
  case
    build_repos_delete_file_request(
      owner: owner,
      repo: repo,
      path_2: path_2,
      body: body,
    )
  {
    Ok(req) ->
      await_response(async_send(req), decode_repos_delete_file_response)
    Error(error) -> transport.resolve(Error(error))
  }
}

/// Build the transport request for repos_delete_file without sending it. Useful for testing and for adding custom transport middleware.
pub fn build_repos_delete_file_request(
  owner owner: String,
  repo repo: String,
  path_2 path_2: String,
  body body: types.ReposDeleteFileRequest,
) -> Result(transport.Request, ClientError) {
  let path = "/repos/{owner}/{repo}/contents/{path}"
  let path = string.replace(path, "{owner}", uri.percent_encode(owner))
  let path = string.replace(path, "{repo}", uri.percent_encode(repo))
  let path = string.replace(path, "{path}", uri.percent_encode(path_2))
  let query = []
  let headers = []
  let body = transport.TextBody(encode.encode_repos_delete_file_request(body))
  let headers = [#("content-type", "application/json"), ..headers]
  Ok(
    transport.Request(
      method: transport.Delete,
      base_url: Some(default_base_url()),
      path: path,
      query: query,
      headers: headers,
      body: body,
      security: [],
    ),
  )
}

/// Decode a transport response into the typed response variant for repos_delete_file.
pub fn decode_repos_delete_file_response(
  resp: transport.Response,
) -> Result(response_types.ReposDeleteFileResponse, ClientError) {
  case resp.status {
    200 -> {
      use text <- result.try(text_body(resp.body))
      case decode.decode_file_commit(text) {
        Ok(decoded) -> Ok(response_types.ReposDeleteFileResponseOk(decoded))
        Error(_) ->
          Error(DecodeFailure(detail: "Failed to decode response body"))
      }
    }
    404 -> {
      use text <- result.try(text_body(resp.body))
      case decode.decode_basic_error(text) {
        Ok(decoded) ->
          Ok(response_types.ReposDeleteFileResponseNotFound(decoded))
        Error(_) ->
          Error(DecodeFailure(detail: "Failed to decode response body"))
      }
    }
    409 -> {
      use text <- result.try(text_body(resp.body))
      case decode.decode_basic_error(text) {
        Ok(decoded) ->
          Ok(response_types.ReposDeleteFileResponseConflict(decoded))
        Error(_) ->
          Error(DecodeFailure(detail: "Failed to decode response body"))
      }
    }
    422 -> {
      use text <- result.try(text_body(resp.body))
      case decode.decode_validation_error(text) {
        Ok(decoded) ->
          Ok(response_types.ReposDeleteFileResponseUnprocessableEntity(decoded))
        Error(_) ->
          Error(DecodeFailure(detail: "Failed to decode response body"))
      }
    }
    503 -> {
      use text <- result.try(text_body(resp.body))
      case decode.decode_repos_delete_file_response_service_unavailable(text) {
        Ok(decoded) ->
          Ok(response_types.ReposDeleteFileResponseServiceUnavailable(decoded))
        Error(_) ->
          Error(DecodeFailure(detail: "Failed to decode response body"))
      }
    }
    _ ->
      Error(UnexpectedStatus(
        status: resp.status,
        headers: resp.headers,
        body: resp.body,
      ))
  }
}

/// Request-object wrapper. Delegates to repos_delete_file with fields unpacked from the request record.
pub fn repos_delete_file_with_request(
  send send: transport.Send,
  request request: request_types.ReposDeleteFileRequest,
) -> Result(response_types.ReposDeleteFileResponse, ClientError) {
  repos_delete_file(
    send,
    request.owner,
    request.repo,
    request.path_2,
    request.body,
  )
}

/// Async request-object wrapper. Delegates to repos_delete_file_async with fields unpacked from the request record.
pub fn repos_delete_file_with_request_async(
  async_send async_send: transport.AsyncSend,
  request request: request_types.ReposDeleteFileRequest,
) -> transport.Async(
  Result(response_types.ReposDeleteFileResponse, ClientError),
) {
  repos_delete_file_async(
    async_send,
    request.owner,
    request.repo,
    request.path_2,
    request.body,
  )
}

/// Get an issue comment
/// You can use the REST API to get comments on issues and pull requests. Every pull request is an issue, but not every issue is a pull request.
///
/// This endpoint supports the following custom media types. For more information, see "[Media types](https://docs.github.com/rest/using-the-rest-api/getting-started-with-the-rest-api#media-types)."
///
/// - **`application/vnd.github.raw+json`**: Returns the raw markdown body. Response will include `body`. This is the default if you do not pass any specific media type.
/// - **`application/vnd.github.text+json`**: Returns a text only representation of the markdown body. Response will include `body_text`.
/// - **`application/vnd.github.html+json`**: Returns HTML rendered from the body's markdown. Response will include `body_html`.
/// - **`application/vnd.github.full+json`**: Returns raw, text, and HTML representations. Response will include `body`, `body_text`, and `body_html`.
pub fn issues_get_comment(
  send send: transport.Send,
  owner owner: String,
  repo repo: String,
  comment_id comment_id: Int,
) -> Result(response_types.IssuesGetCommentResponse, ClientError) {
  use req <- result.try(build_issues_get_comment_request(
    owner: owner,
    repo: repo,
    comment_id: comment_id,
  ))
  use resp <- result.try(
    send(req)
    |> result.map_error(TransportError),
  )
  decode_issues_get_comment_response(resp)
}

/// Async transport variant of issues_get_comment. Resolves to the typed response or a client error.
pub fn issues_get_comment_async(
  async_send async_send: transport.AsyncSend,
  owner owner: String,
  repo repo: String,
  comment_id comment_id: Int,
) -> transport.Async(
  Result(response_types.IssuesGetCommentResponse, ClientError),
) {
  case
    build_issues_get_comment_request(
      owner: owner,
      repo: repo,
      comment_id: comment_id,
    )
  {
    Ok(req) ->
      await_response(async_send(req), decode_issues_get_comment_response)
    Error(error) -> transport.resolve(Error(error))
  }
}

/// Build the transport request for issues_get_comment without sending it. Useful for testing and for adding custom transport middleware.
pub fn build_issues_get_comment_request(
  owner owner: String,
  repo repo: String,
  comment_id comment_id: Int,
) -> Result(transport.Request, ClientError) {
  let path = "/repos/{owner}/{repo}/issues/comments/{comment_id}"
  let path = string.replace(path, "{owner}", uri.percent_encode(owner))
  let path = string.replace(path, "{repo}", uri.percent_encode(repo))
  let path =
    string.replace(
      path,
      "{comment_id}",
      uri.percent_encode(int.to_string(comment_id)),
    )
  let query = []
  let headers = []
  let body = transport.EmptyBody
  Ok(
    transport.Request(
      method: transport.Get,
      base_url: Some(default_base_url()),
      path: path,
      query: query,
      headers: headers,
      body: body,
      security: [],
    ),
  )
}

/// Decode a transport response into the typed response variant for issues_get_comment.
pub fn decode_issues_get_comment_response(
  resp: transport.Response,
) -> Result(response_types.IssuesGetCommentResponse, ClientError) {
  case resp.status {
    200 -> {
      use text <- result.try(text_body(resp.body))
      case decode.decode_issue_comment(text) {
        Ok(decoded) -> Ok(response_types.IssuesGetCommentResponseOk(decoded))
        Error(_) ->
          Error(DecodeFailure(detail: "Failed to decode response body"))
      }
    }
    404 -> {
      use text <- result.try(text_body(resp.body))
      case decode.decode_basic_error(text) {
        Ok(decoded) ->
          Ok(response_types.IssuesGetCommentResponseNotFound(decoded))
        Error(_) ->
          Error(DecodeFailure(detail: "Failed to decode response body"))
      }
    }
    _ ->
      Error(UnexpectedStatus(
        status: resp.status,
        headers: resp.headers,
        body: resp.body,
      ))
  }
}

/// Request-object wrapper. Delegates to issues_get_comment with fields unpacked from the request record.
pub fn issues_get_comment_with_request(
  send send: transport.Send,
  request request: request_types.IssuesGetCommentRequest,
) -> Result(response_types.IssuesGetCommentResponse, ClientError) {
  issues_get_comment(send, request.owner, request.repo, request.comment_id)
}

/// Async request-object wrapper. Delegates to issues_get_comment_async with fields unpacked from the request record.
pub fn issues_get_comment_with_request_async(
  async_send async_send: transport.AsyncSend,
  request request: request_types.IssuesGetCommentRequest,
) -> transport.Async(
  Result(response_types.IssuesGetCommentResponse, ClientError),
) {
  issues_get_comment_async(
    async_send,
    request.owner,
    request.repo,
    request.comment_id,
  )
}

/// Delete an issue comment
/// You can use the REST API to delete comments on issues and pull requests. Every pull request is an issue, but not every issue is a pull request.
pub fn issues_delete_comment(
  send send: transport.Send,
  owner owner: String,
  repo repo: String,
  comment_id comment_id: Int,
) -> Result(response_types.IssuesDeleteCommentResponse, ClientError) {
  use req <- result.try(build_issues_delete_comment_request(
    owner: owner,
    repo: repo,
    comment_id: comment_id,
  ))
  use resp <- result.try(
    send(req)
    |> result.map_error(TransportError),
  )
  decode_issues_delete_comment_response(resp)
}

/// Async transport variant of issues_delete_comment. Resolves to the typed response or a client error.
pub fn issues_delete_comment_async(
  async_send async_send: transport.AsyncSend,
  owner owner: String,
  repo repo: String,
  comment_id comment_id: Int,
) -> transport.Async(
  Result(response_types.IssuesDeleteCommentResponse, ClientError),
) {
  case
    build_issues_delete_comment_request(
      owner: owner,
      repo: repo,
      comment_id: comment_id,
    )
  {
    Ok(req) ->
      await_response(async_send(req), decode_issues_delete_comment_response)
    Error(error) -> transport.resolve(Error(error))
  }
}

/// Build the transport request for issues_delete_comment without sending it. Useful for testing and for adding custom transport middleware.
pub fn build_issues_delete_comment_request(
  owner owner: String,
  repo repo: String,
  comment_id comment_id: Int,
) -> Result(transport.Request, ClientError) {
  let path = "/repos/{owner}/{repo}/issues/comments/{comment_id}"
  let path = string.replace(path, "{owner}", uri.percent_encode(owner))
  let path = string.replace(path, "{repo}", uri.percent_encode(repo))
  let path =
    string.replace(
      path,
      "{comment_id}",
      uri.percent_encode(int.to_string(comment_id)),
    )
  let query = []
  let headers = []
  let body = transport.EmptyBody
  Ok(
    transport.Request(
      method: transport.Delete,
      base_url: Some(default_base_url()),
      path: path,
      query: query,
      headers: headers,
      body: body,
      security: [],
    ),
  )
}

/// Decode a transport response into the typed response variant for issues_delete_comment.
pub fn decode_issues_delete_comment_response(
  resp: transport.Response,
) -> Result(response_types.IssuesDeleteCommentResponse, ClientError) {
  case resp.status {
    204 -> Ok(response_types.IssuesDeleteCommentResponseNoContent)
    _ ->
      Error(UnexpectedStatus(
        status: resp.status,
        headers: resp.headers,
        body: resp.body,
      ))
  }
}

/// Request-object wrapper. Delegates to issues_delete_comment with fields unpacked from the request record.
pub fn issues_delete_comment_with_request(
  send send: transport.Send,
  request request: request_types.IssuesDeleteCommentRequest,
) -> Result(response_types.IssuesDeleteCommentResponse, ClientError) {
  issues_delete_comment(send, request.owner, request.repo, request.comment_id)
}

/// Async request-object wrapper. Delegates to issues_delete_comment_async with fields unpacked from the request record.
pub fn issues_delete_comment_with_request_async(
  async_send async_send: transport.AsyncSend,
  request request: request_types.IssuesDeleteCommentRequest,
) -> transport.Async(
  Result(response_types.IssuesDeleteCommentResponse, ClientError),
) {
  issues_delete_comment_async(
    async_send,
    request.owner,
    request.repo,
    request.comment_id,
  )
}

/// Update an issue comment
/// You can use the REST API to update comments on issues and pull requests. Every pull request is an issue, but not every issue is a pull request.
///
/// This endpoint supports the following custom media types. For more information, see "[Media types](https://docs.github.com/rest/using-the-rest-api/getting-started-with-the-rest-api#media-types)."
///
/// - **`application/vnd.github.raw+json`**: Returns the raw markdown body. Response will include `body`. This is the default if you do not pass any specific media type.
/// - **`application/vnd.github.text+json`**: Returns a text only representation of the markdown body. Response will include `body_text`.
/// - **`application/vnd.github.html+json`**: Returns HTML rendered from the body's markdown. Response will include `body_html`.
/// - **`application/vnd.github.full+json`**: Returns raw, text, and HTML representations. Response will include `body`, `body_text`, and `body_html`.
pub fn issues_update_comment(
  send send: transport.Send,
  owner owner: String,
  repo repo: String,
  comment_id comment_id: Int,
  body body: types.IssuesUpdateCommentRequest,
) -> Result(response_types.IssuesUpdateCommentResponse, ClientError) {
  use req <- result.try(build_issues_update_comment_request(
    owner: owner,
    repo: repo,
    comment_id: comment_id,
    body: body,
  ))
  use resp <- result.try(
    send(req)
    |> result.map_error(TransportError),
  )
  decode_issues_update_comment_response(resp)
}

/// Async transport variant of issues_update_comment. Resolves to the typed response or a client error.
pub fn issues_update_comment_async(
  async_send async_send: transport.AsyncSend,
  owner owner: String,
  repo repo: String,
  comment_id comment_id: Int,
  body body: types.IssuesUpdateCommentRequest,
) -> transport.Async(
  Result(response_types.IssuesUpdateCommentResponse, ClientError),
) {
  case
    build_issues_update_comment_request(
      owner: owner,
      repo: repo,
      comment_id: comment_id,
      body: body,
    )
  {
    Ok(req) ->
      await_response(async_send(req), decode_issues_update_comment_response)
    Error(error) -> transport.resolve(Error(error))
  }
}

/// Build the transport request for issues_update_comment without sending it. Useful for testing and for adding custom transport middleware.
pub fn build_issues_update_comment_request(
  owner owner: String,
  repo repo: String,
  comment_id comment_id: Int,
  body body: types.IssuesUpdateCommentRequest,
) -> Result(transport.Request, ClientError) {
  let path = "/repos/{owner}/{repo}/issues/comments/{comment_id}"
  let path = string.replace(path, "{owner}", uri.percent_encode(owner))
  let path = string.replace(path, "{repo}", uri.percent_encode(repo))
  let path =
    string.replace(
      path,
      "{comment_id}",
      uri.percent_encode(int.to_string(comment_id)),
    )
  let query = []
  let headers = []
  let body =
    transport.TextBody(encode.encode_issues_update_comment_request(body))
  let headers = [#("content-type", "application/json"), ..headers]
  Ok(
    transport.Request(
      method: transport.Patch,
      base_url: Some(default_base_url()),
      path: path,
      query: query,
      headers: headers,
      body: body,
      security: [],
    ),
  )
}

/// Decode a transport response into the typed response variant for issues_update_comment.
pub fn decode_issues_update_comment_response(
  resp: transport.Response,
) -> Result(response_types.IssuesUpdateCommentResponse, ClientError) {
  case resp.status {
    200 -> {
      use text <- result.try(text_body(resp.body))
      case decode.decode_issue_comment(text) {
        Ok(decoded) -> Ok(response_types.IssuesUpdateCommentResponseOk(decoded))
        Error(_) ->
          Error(DecodeFailure(detail: "Failed to decode response body"))
      }
    }
    422 -> {
      use text <- result.try(text_body(resp.body))
      case decode.decode_validation_error(text) {
        Ok(decoded) ->
          Ok(response_types.IssuesUpdateCommentResponseUnprocessableEntity(
            decoded,
          ))
        Error(_) ->
          Error(DecodeFailure(detail: "Failed to decode response body"))
      }
    }
    _ ->
      Error(UnexpectedStatus(
        status: resp.status,
        headers: resp.headers,
        body: resp.body,
      ))
  }
}

/// Request-object wrapper. Delegates to issues_update_comment with fields unpacked from the request record.
pub fn issues_update_comment_with_request(
  send send: transport.Send,
  request request: request_types.IssuesUpdateCommentRequest,
) -> Result(response_types.IssuesUpdateCommentResponse, ClientError) {
  issues_update_comment(
    send,
    request.owner,
    request.repo,
    request.comment_id,
    request.body,
  )
}

/// Async request-object wrapper. Delegates to issues_update_comment_async with fields unpacked from the request record.
pub fn issues_update_comment_with_request_async(
  async_send async_send: transport.AsyncSend,
  request request: request_types.IssuesUpdateCommentRequest,
) -> transport.Async(
  Result(response_types.IssuesUpdateCommentResponse, ClientError),
) {
  issues_update_comment_async(
    async_send,
    request.owner,
    request.repo,
    request.comment_id,
    request.body,
  )
}

/// List issue comments
/// You can use the REST API to list comments on issues and pull requests. Every pull request is an issue, but not every issue is a pull request.
///
/// Issue comments are ordered by ascending ID.
///
/// This endpoint supports the following custom media types. For more information, see "[Media types](https://docs.github.com/rest/using-the-rest-api/getting-started-with-the-rest-api#media-types)."
///
/// - **`application/vnd.github.raw+json`**: Returns the raw markdown body. Response will include `body`. This is the default if you do not pass any specific media type.
/// - **`application/vnd.github.text+json`**: Returns a text only representation of the markdown body. Response will include `body_text`.
/// - **`application/vnd.github.html+json`**: Returns HTML rendered from the body's markdown. Response will include `body_html`.
/// - **`application/vnd.github.full+json`**: Returns raw, text, and HTML representations. Response will include `body`, `body_text`, and `body_html`.
pub fn issues_list_comments(
  send send: transport.Send,
  owner owner: String,
  repo repo: String,
  issue_number issue_number: Int,
  since since: Option(String),
  per_page per_page: Option(Int),
  page page: Option(Int),
) -> Result(response_types.IssuesListCommentsResponse, ClientError) {
  use req <- result.try(build_issues_list_comments_request(
    owner: owner,
    repo: repo,
    issue_number: issue_number,
    since: since,
    per_page: per_page,
    page: page,
  ))
  use resp <- result.try(
    send(req)
    |> result.map_error(TransportError),
  )
  decode_issues_list_comments_response(resp)
}

/// Async transport variant of issues_list_comments. Resolves to the typed response or a client error.
pub fn issues_list_comments_async(
  async_send async_send: transport.AsyncSend,
  owner owner: String,
  repo repo: String,
  issue_number issue_number: Int,
  since since: Option(String),
  per_page per_page: Option(Int),
  page page: Option(Int),
) -> transport.Async(
  Result(response_types.IssuesListCommentsResponse, ClientError),
) {
  case
    build_issues_list_comments_request(
      owner: owner,
      repo: repo,
      issue_number: issue_number,
      since: since,
      per_page: per_page,
      page: page,
    )
  {
    Ok(req) ->
      await_response(async_send(req), decode_issues_list_comments_response)
    Error(error) -> transport.resolve(Error(error))
  }
}

/// Build the transport request for issues_list_comments without sending it. Useful for testing and for adding custom transport middleware.
pub fn build_issues_list_comments_request(
  owner owner: String,
  repo repo: String,
  issue_number issue_number: Int,
  since since: Option(String),
  per_page per_page: Option(Int),
  page page: Option(Int),
) -> Result(transport.Request, ClientError) {
  let path = "/repos/{owner}/{repo}/issues/{issue_number}/comments"
  let path = string.replace(path, "{owner}", uri.percent_encode(owner))
  let path = string.replace(path, "{repo}", uri.percent_encode(repo))
  let path =
    string.replace(
      path,
      "{issue_number}",
      uri.percent_encode(int.to_string(issue_number)),
    )
  let query = []
  let query = case since {
    Some(v) -> [#("since", v), ..query]
    None -> query
  }
  let query = case per_page {
    Some(v) -> [#("per_page", int.to_string(v)), ..query]
    None -> query
  }
  let query = case page {
    Some(v) -> [#("page", int.to_string(v)), ..query]
    None -> query
  }
  let query = list.reverse(query)
  let headers = []
  let body = transport.EmptyBody
  Ok(
    transport.Request(
      method: transport.Get,
      base_url: Some(default_base_url()),
      path: path,
      query: query,
      headers: headers,
      body: body,
      security: [],
    ),
  )
}

/// Decode a transport response into the typed response variant for issues_list_comments.
pub fn decode_issues_list_comments_response(
  resp: transport.Response,
) -> Result(response_types.IssuesListCommentsResponse, ClientError) {
  case resp.status {
    200 -> {
      use text <- result.try(text_body(resp.body))
      let link =
        list.key_find(resp.headers, "link")
        |> result.map(Some)
        |> result.unwrap(None)
      case json.parse(text, dyn_decode.list(decode.issue_comment_decoder())) {
        Ok(decoded) ->
          Ok(response_types.IssuesListCommentsResponseOk(
            decoded,
            response_types.IssuesListCommentsResponseOkHeaders(link: link),
          ))
        Error(_) ->
          Error(DecodeFailure(detail: "Failed to decode response body"))
      }
    }
    404 -> {
      use text <- result.try(text_body(resp.body))
      case decode.decode_basic_error(text) {
        Ok(decoded) ->
          Ok(response_types.IssuesListCommentsResponseNotFound(decoded))
        Error(_) ->
          Error(DecodeFailure(detail: "Failed to decode response body"))
      }
    }
    410 -> {
      use text <- result.try(text_body(resp.body))
      case decode.decode_basic_error(text) {
        Ok(decoded) ->
          Ok(response_types.IssuesListCommentsResponseGone(decoded))
        Error(_) ->
          Error(DecodeFailure(detail: "Failed to decode response body"))
      }
    }
    _ ->
      Error(UnexpectedStatus(
        status: resp.status,
        headers: resp.headers,
        body: resp.body,
      ))
  }
}

/// Request-object wrapper. Delegates to issues_list_comments with fields unpacked from the request record.
pub fn issues_list_comments_with_request(
  send send: transport.Send,
  request request: request_types.IssuesListCommentsRequest,
) -> Result(response_types.IssuesListCommentsResponse, ClientError) {
  issues_list_comments(
    send,
    request.owner,
    request.repo,
    request.issue_number,
    request.since,
    request.per_page,
    request.page,
  )
}

/// Async request-object wrapper. Delegates to issues_list_comments_async with fields unpacked from the request record.
pub fn issues_list_comments_with_request_async(
  async_send async_send: transport.AsyncSend,
  request request: request_types.IssuesListCommentsRequest,
) -> transport.Async(
  Result(response_types.IssuesListCommentsResponse, ClientError),
) {
  issues_list_comments_async(
    async_send,
    request.owner,
    request.repo,
    request.issue_number,
    request.since,
    request.per_page,
    request.page,
  )
}

/// Create an issue comment
/// You can use the REST API to create comments on issues and pull requests. Every pull request is an issue, but not every issue is a pull request.
///
/// This endpoint triggers [notifications](https://docs.github.com/github/managing-subscriptions-and-notifications-on-github/about-notifications).
/// Creating content too quickly using this endpoint may result in secondary rate limiting.
/// For more information, see "[Rate limits for the API](https://docs.github.com/rest/using-the-rest-api/rate-limits-for-the-rest-api#about-secondary-rate-limits)"
/// and "[Best practices for using the REST API](https://docs.github.com/rest/guides/best-practices-for-using-the-rest-api)."
///
/// This endpoint supports the following custom media types. For more information, see "[Media types](https://docs.github.com/rest/using-the-rest-api/getting-started-with-the-rest-api#media-types)."
///
/// - **`application/vnd.github.raw+json`**: Returns the raw markdown body. Response will include `body`. This is the default if you do not pass any specific media type.
/// - **`application/vnd.github.text+json`**: Returns a text only representation of the markdown body. Response will include `body_text`.
/// - **`application/vnd.github.html+json`**: Returns HTML rendered from the body's markdown. Response will include `body_html`.
/// - **`application/vnd.github.full+json`**: Returns raw, text, and HTML representations. Response will include `body`, `body_text`, and `body_html`.
pub fn issues_create_comment(
  send send: transport.Send,
  owner owner: String,
  repo repo: String,
  issue_number issue_number: Int,
  body body: types.IssuesCreateCommentRequest,
) -> Result(response_types.IssuesCreateCommentResponse, ClientError) {
  use req <- result.try(build_issues_create_comment_request(
    owner: owner,
    repo: repo,
    issue_number: issue_number,
    body: body,
  ))
  use resp <- result.try(
    send(req)
    |> result.map_error(TransportError),
  )
  decode_issues_create_comment_response(resp)
}

/// Async transport variant of issues_create_comment. Resolves to the typed response or a client error.
pub fn issues_create_comment_async(
  async_send async_send: transport.AsyncSend,
  owner owner: String,
  repo repo: String,
  issue_number issue_number: Int,
  body body: types.IssuesCreateCommentRequest,
) -> transport.Async(
  Result(response_types.IssuesCreateCommentResponse, ClientError),
) {
  case
    build_issues_create_comment_request(
      owner: owner,
      repo: repo,
      issue_number: issue_number,
      body: body,
    )
  {
    Ok(req) ->
      await_response(async_send(req), decode_issues_create_comment_response)
    Error(error) -> transport.resolve(Error(error))
  }
}

/// Build the transport request for issues_create_comment without sending it. Useful for testing and for adding custom transport middleware.
pub fn build_issues_create_comment_request(
  owner owner: String,
  repo repo: String,
  issue_number issue_number: Int,
  body body: types.IssuesCreateCommentRequest,
) -> Result(transport.Request, ClientError) {
  let path = "/repos/{owner}/{repo}/issues/{issue_number}/comments"
  let path = string.replace(path, "{owner}", uri.percent_encode(owner))
  let path = string.replace(path, "{repo}", uri.percent_encode(repo))
  let path =
    string.replace(
      path,
      "{issue_number}",
      uri.percent_encode(int.to_string(issue_number)),
    )
  let query = []
  let headers = []
  let body =
    transport.TextBody(encode.encode_issues_create_comment_request(body))
  let headers = [#("content-type", "application/json"), ..headers]
  Ok(
    transport.Request(
      method: transport.Post,
      base_url: Some(default_base_url()),
      path: path,
      query: query,
      headers: headers,
      body: body,
      security: [],
    ),
  )
}

/// Decode a transport response into the typed response variant for issues_create_comment.
pub fn decode_issues_create_comment_response(
  resp: transport.Response,
) -> Result(response_types.IssuesCreateCommentResponse, ClientError) {
  case resp.status {
    201 -> {
      use text <- result.try(text_body(resp.body))
      let location =
        list.key_find(resp.headers, "location")
        |> result.map(Some)
        |> result.unwrap(None)
      case decode.decode_issue_comment(text) {
        Ok(decoded) ->
          Ok(response_types.IssuesCreateCommentResponseCreated(
            decoded,
            response_types.IssuesCreateCommentResponseCreatedHeaders(
              location: location,
            ),
          ))
        Error(_) ->
          Error(DecodeFailure(detail: "Failed to decode response body"))
      }
    }
    403 -> {
      use text <- result.try(text_body(resp.body))
      case decode.decode_basic_error(text) {
        Ok(decoded) ->
          Ok(response_types.IssuesCreateCommentResponseForbidden(decoded))
        Error(_) ->
          Error(DecodeFailure(detail: "Failed to decode response body"))
      }
    }
    404 -> {
      use text <- result.try(text_body(resp.body))
      case decode.decode_basic_error(text) {
        Ok(decoded) ->
          Ok(response_types.IssuesCreateCommentResponseNotFound(decoded))
        Error(_) ->
          Error(DecodeFailure(detail: "Failed to decode response body"))
      }
    }
    410 -> {
      use text <- result.try(text_body(resp.body))
      case decode.decode_basic_error(text) {
        Ok(decoded) ->
          Ok(response_types.IssuesCreateCommentResponseGone(decoded))
        Error(_) ->
          Error(DecodeFailure(detail: "Failed to decode response body"))
      }
    }
    422 -> {
      use text <- result.try(text_body(resp.body))
      case decode.decode_validation_error(text) {
        Ok(decoded) ->
          Ok(response_types.IssuesCreateCommentResponseUnprocessableEntity(
            decoded,
          ))
        Error(_) ->
          Error(DecodeFailure(detail: "Failed to decode response body"))
      }
    }
    _ ->
      Error(UnexpectedStatus(
        status: resp.status,
        headers: resp.headers,
        body: resp.body,
      ))
  }
}

/// Request-object wrapper. Delegates to issues_create_comment with fields unpacked from the request record.
pub fn issues_create_comment_with_request(
  send send: transport.Send,
  request request: request_types.IssuesCreateCommentRequest,
) -> Result(response_types.IssuesCreateCommentResponse, ClientError) {
  issues_create_comment(
    send,
    request.owner,
    request.repo,
    request.issue_number,
    request.body,
  )
}

/// Async request-object wrapper. Delegates to issues_create_comment_async with fields unpacked from the request record.
pub fn issues_create_comment_with_request_async(
  async_send async_send: transport.AsyncSend,
  request request: request_types.IssuesCreateCommentRequest,
) -> transport.Async(
  Result(response_types.IssuesCreateCommentResponse, ClientError),
) {
  issues_create_comment_async(
    async_send,
    request.owner,
    request.repo,
    request.issue_number,
    request.body,
  )
}
