// Code generated by oaspec v0.69.0. DO NOT EDIT.

import dco_check/internal/github/types
import gleam/dict
import gleam/json
import gleam/list
import gleam/option.{type Option}

pub fn encode_content_directory_item_type_json(
  value: types.ContentDirectoryItemType,
) -> json.Json {
  let str = case value {
    types.ContentDirectoryItemTypeDir -> "dir"
    types.ContentDirectoryItemTypeFile -> "file"
    types.ContentDirectoryItemTypeSubmodule -> "submodule"
    types.ContentDirectoryItemTypeSymlink -> "symlink"
  }
  json.string(str)
}

pub fn encode_content_directory_item_type(
  value: types.ContentDirectoryItemType,
) -> String {
  encode_content_directory_item_type_json(value) |> json.to_string()
}

pub fn encode_content_directory_item_type_to_string(
  value: types.ContentDirectoryItemType,
) -> String {
  case value {
    types.ContentDirectoryItemTypeDir -> "dir"
    types.ContentDirectoryItemTypeFile -> "file"
    types.ContentDirectoryItemTypeSubmodule -> "submodule"
    types.ContentDirectoryItemTypeSymlink -> "symlink"
  }
}

pub fn encode_commit_comparison_status_json(
  value: types.CommitComparisonStatus,
) -> json.Json {
  let str = case value {
    types.CommitComparisonStatusDiverged -> "diverged"
    types.CommitComparisonStatusAhead -> "ahead"
    types.CommitComparisonStatusBehind -> "behind"
    types.CommitComparisonStatusIdentical -> "identical"
  }
  json.string(str)
}

pub fn encode_commit_comparison_status(
  value: types.CommitComparisonStatus,
) -> String {
  encode_commit_comparison_status_json(value) |> json.to_string()
}

pub fn encode_commit_comparison_status_to_string(
  value: types.CommitComparisonStatus,
) -> String {
  case value {
    types.CommitComparisonStatusDiverged -> "diverged"
    types.CommitComparisonStatusAhead -> "ahead"
    types.CommitComparisonStatusBehind -> "behind"
    types.CommitComparisonStatusIdentical -> "identical"
  }
}

pub fn encode_diff_entry_status_json(
  value: types.DiffEntryStatus,
) -> json.Json {
  let str = case value {
    types.DiffEntryStatusAdded -> "added"
    types.DiffEntryStatusRemoved -> "removed"
    types.DiffEntryStatusModified -> "modified"
    types.DiffEntryStatusRenamed -> "renamed"
    types.DiffEntryStatusCopied -> "copied"
    types.DiffEntryStatusChanged -> "changed"
    types.DiffEntryStatusUnchanged -> "unchanged"
  }
  json.string(str)
}

pub fn encode_diff_entry_status(value: types.DiffEntryStatus) -> String {
  encode_diff_entry_status_json(value) |> json.to_string()
}

pub fn encode_diff_entry_status_to_string(
  value: types.DiffEntryStatus,
) -> String {
  case value {
    types.DiffEntryStatusAdded -> "added"
    types.DiffEntryStatusRemoved -> "removed"
    types.DiffEntryStatusModified -> "modified"
    types.DiffEntryStatusRenamed -> "renamed"
    types.DiffEntryStatusCopied -> "copied"
    types.DiffEntryStatusChanged -> "changed"
    types.DiffEntryStatusUnchanged -> "unchanged"
  }
}

pub fn encode_commit_author_json(value: types.CommitAuthor) -> json.Json {
  case value {
    types.CommitAuthorSimpleUser(inner) -> encode_simple_user_json(inner)
    types.CommitAuthorEmptyObject(inner) -> encode_empty_object_json(inner)
  }
}

pub fn encode_commit_author(value: types.CommitAuthor) -> String {
  encode_commit_author_json(value) |> json.to_string()
}

pub fn encode_commit_commit_json(value: types.CommitCommit) -> json.Json {
  json.object(
    list.flatten([
      [
        #(
          "author",
          json.nullable(value.author, encode_commit_commit_author_json),
        ),
      ],
      [#("comment_count", json.int(value.comment_count))],
      [
        #(
          "committer",
          json.nullable(value.committer, encode_commit_commit_committer_json),
        ),
      ],
      [#("message", json.string(value.message))],
      [#("tree", encode_commit_commit_tree_json(value.tree))],
      [#("url", json.string(value.url))],
      case value.verification {
        option.None -> []
        option.Some(x) -> [#("verification", encode_verification_json(x))]
      },
    ]),
  )
}

pub fn encode_commit_commit(value: types.CommitCommit) -> String {
  encode_commit_commit_json(value) |> json.to_string()
}

pub fn encode_commit_commit_author_json(
  value: types.CommitCommitAuthor,
) -> json.Json {
  case value.git_user {
    option.Some(v) -> encode_git_user_json(v)
    option.None -> json.null()
  }
}

pub fn encode_commit_commit_author(value: types.CommitCommitAuthor) -> String {
  encode_commit_commit_author_json(value) |> json.to_string()
}

pub fn encode_commit_commit_committer_json(
  value: types.CommitCommitCommitter,
) -> json.Json {
  case value.git_user {
    option.Some(v) -> encode_git_user_json(v)
    option.None -> json.null()
  }
}

pub fn encode_commit_commit_committer(
  value: types.CommitCommitCommitter,
) -> String {
  encode_commit_commit_committer_json(value) |> json.to_string()
}

pub fn encode_commit_commit_tree_json(
  value: types.CommitCommitTree,
) -> json.Json {
  json.object([
    #("sha", json.string(value.sha)),
    #("url", json.string(value.url)),
  ])
}

pub fn encode_commit_commit_tree(value: types.CommitCommitTree) -> String {
  encode_commit_commit_tree_json(value) |> json.to_string()
}

pub fn encode_commit_committer_json(value: types.CommitCommitter) -> json.Json {
  case value {
    types.CommitCommitterSimpleUser(inner) -> encode_simple_user_json(inner)
    types.CommitCommitterEmptyObject(inner) -> encode_empty_object_json(inner)
  }
}

pub fn encode_commit_committer(value: types.CommitCommitter) -> String {
  encode_commit_committer_json(value) |> json.to_string()
}

pub fn encode_commit_parents_json(
  value: List(types.CommitParentsItem),
) -> json.Json {
  json.array(value, encode_commit_parents_item_json)
}

pub fn encode_commit_parents(value: List(types.CommitParentsItem)) -> String {
  encode_commit_parents_json(value) |> json.to_string()
}

pub fn encode_commit_parents_item_json(
  value: types.CommitParentsItem,
) -> json.Json {
  json.object(
    list.flatten([
      case value.html_url {
        option.None -> []
        option.Some(x) -> [#("html_url", json.string(x))]
      },
      [#("sha", json.string(value.sha))],
      [#("url", json.string(value.url))],
    ]),
  )
}

pub fn encode_commit_parents_item(value: types.CommitParentsItem) -> String {
  encode_commit_parents_item_json(value) |> json.to_string()
}

pub fn encode_commit_stats_json(value: types.CommitStats) -> json.Json {
  json.object(
    list.flatten([
      case value.additions {
        option.None -> []
        option.Some(x) -> [#("additions", json.int(x))]
      },
      case value.deletions {
        option.None -> []
        option.Some(x) -> [#("deletions", json.int(x))]
      },
      case value.total {
        option.None -> []
        option.Some(x) -> [#("total", json.int(x))]
      },
    ]),
  )
}

pub fn encode_commit_stats(value: types.CommitStats) -> String {
  encode_commit_stats_json(value) |> json.to_string()
}

pub fn encode_content_directory_item_json(
  value: types.ContentDirectoryItem,
) -> json.Json {
  json.object(
    list.flatten([
      [#("_links", encode_content_directory_item_links_json(value.links))],
      case value.content {
        option.None -> []
        option.Some(x) -> [#("content", json.string(x))]
      },
      [#("download_url", json.nullable(value.download_url, json.string))],
      [#("git_url", json.nullable(value.git_url, json.string))],
      [#("html_url", json.nullable(value.html_url, json.string))],
      [#("name", json.string(value.name))],
      [#("path", json.string(value.path))],
      [#("sha", json.string(value.sha))],
      [#("size", json.int(value.size))],
      [#("type", encode_content_directory_item_type_json(value.type_))],
      [#("url", json.string(value.url))],
    ]),
  )
}

pub fn encode_content_directory_item(
  value: types.ContentDirectoryItem,
) -> String {
  encode_content_directory_item_json(value) |> json.to_string()
}

pub fn encode_content_directory_item_links_json(
  value: types.ContentDirectoryItemLinks,
) -> json.Json {
  json.object([
    #("git", json.nullable(value.git, json.string)),
    #("html", json.nullable(value.html, json.string)),
    #("self", json.string(value.self)),
  ])
}

pub fn encode_content_directory_item_links(
  value: types.ContentDirectoryItemLinks,
) -> String {
  encode_content_directory_item_links_json(value) |> json.to_string()
}

pub fn encode_content_file_links_json(
  value: types.ContentFileLinks,
) -> json.Json {
  json.object([
    #("git", json.nullable(value.git, json.string)),
    #("html", json.nullable(value.html, json.string)),
    #("self", json.string(value.self)),
  ])
}

pub fn encode_content_file_links(value: types.ContentFileLinks) -> String {
  encode_content_file_links_json(value) |> json.to_string()
}

pub fn encode_content_submodule_links_json(
  value: types.ContentSubmoduleLinks,
) -> json.Json {
  json.object([
    #("git", json.nullable(value.git, json.string)),
    #("html", json.nullable(value.html, json.string)),
    #("self", json.string(value.self)),
  ])
}

pub fn encode_content_submodule_links(
  value: types.ContentSubmoduleLinks,
) -> String {
  encode_content_submodule_links_json(value) |> json.to_string()
}

pub fn encode_content_symlink_links_json(
  value: types.ContentSymlinkLinks,
) -> json.Json {
  json.object([
    #("git", json.nullable(value.git, json.string)),
    #("html", json.nullable(value.html, json.string)),
    #("self", json.string(value.self)),
  ])
}

pub fn encode_content_symlink_links(
  value: types.ContentSymlinkLinks,
) -> String {
  encode_content_symlink_links_json(value) |> json.to_string()
}

pub fn encode_content_tree_entries_json(
  value: List(types.ContentTreeEntriesItem),
) -> json.Json {
  json.array(value, encode_content_tree_entries_item_json)
}

pub fn encode_content_tree_entries(
  value: List(types.ContentTreeEntriesItem),
) -> String {
  encode_content_tree_entries_json(value) |> json.to_string()
}

pub fn encode_content_tree_entries_item_json(
  value: types.ContentTreeEntriesItem,
) -> json.Json {
  json.object([
    #("_links", encode_content_tree_entries_item_links_json(value.links)),
    #("download_url", json.nullable(value.download_url, json.string)),
    #("git_url", json.nullable(value.git_url, json.string)),
    #("html_url", json.nullable(value.html_url, json.string)),
    #("name", json.string(value.name)),
    #("path", json.string(value.path)),
    #("sha", json.string(value.sha)),
    #("size", json.int(value.size)),
    #("type", json.string(value.type_)),
    #("url", json.string(value.url)),
  ])
}

pub fn encode_content_tree_entries_item(
  value: types.ContentTreeEntriesItem,
) -> String {
  encode_content_tree_entries_item_json(value) |> json.to_string()
}

pub fn encode_content_tree_entries_item_links_json(
  value: types.ContentTreeEntriesItemLinks,
) -> json.Json {
  json.object([
    #("git", json.nullable(value.git, json.string)),
    #("html", json.nullable(value.html, json.string)),
    #("self", json.string(value.self)),
  ])
}

pub fn encode_content_tree_entries_item_links(
  value: types.ContentTreeEntriesItemLinks,
) -> String {
  encode_content_tree_entries_item_links_json(value) |> json.to_string()
}

pub fn encode_content_tree_links_json(
  value: types.ContentTreeLinks,
) -> json.Json {
  json.object([
    #("git", json.nullable(value.git, json.string)),
    #("html", json.nullable(value.html, json.string)),
    #("self", json.string(value.self)),
  ])
}

pub fn encode_content_tree_links(value: types.ContentTreeLinks) -> String {
  encode_content_tree_links_json(value) |> json.to_string()
}

pub fn encode_file_commit_commit_json(
  value: types.FileCommitCommit,
) -> json.Json {
  json.object(
    list.flatten([
      case value.author {
        option.None -> []
        option.Some(x) -> [
          #("author", encode_file_commit_commit_author_json(x)),
        ]
      },
      case value.committer {
        option.None -> []
        option.Some(x) -> [
          #("committer", encode_file_commit_commit_committer_json(x)),
        ]
      },
      case value.html_url {
        option.None -> []
        option.Some(x) -> [#("html_url", json.string(x))]
      },
      case value.message {
        option.None -> []
        option.Some(x) -> [#("message", json.string(x))]
      },
      case value.node_id {
        option.None -> []
        option.Some(x) -> [#("node_id", json.string(x))]
      },
      case value.parents {
        option.None -> []
        option.Some(x) -> [
          #("parents", encode_file_commit_commit_parents_json(x)),
        ]
      },
      case value.sha {
        option.None -> []
        option.Some(x) -> [#("sha", json.string(x))]
      },
      case value.tree {
        option.None -> []
        option.Some(x) -> [#("tree", encode_file_commit_commit_tree_json(x))]
      },
      case value.url {
        option.None -> []
        option.Some(x) -> [#("url", json.string(x))]
      },
      case value.verification {
        option.None -> []
        option.Some(x) -> [
          #("verification", encode_file_commit_commit_verification_json(x)),
        ]
      },
    ]),
  )
}

pub fn encode_file_commit_commit(value: types.FileCommitCommit) -> String {
  encode_file_commit_commit_json(value) |> json.to_string()
}

pub fn encode_file_commit_commit_author_json(
  value: types.FileCommitCommitAuthor,
) -> json.Json {
  json.object(
    list.flatten([
      case value.date {
        option.None -> []
        option.Some(x) -> [#("date", json.string(x))]
      },
      case value.email {
        option.None -> []
        option.Some(x) -> [#("email", json.string(x))]
      },
      case value.name {
        option.None -> []
        option.Some(x) -> [#("name", json.string(x))]
      },
    ]),
  )
}

pub fn encode_file_commit_commit_author(
  value: types.FileCommitCommitAuthor,
) -> String {
  encode_file_commit_commit_author_json(value) |> json.to_string()
}

pub fn encode_file_commit_commit_committer_json(
  value: types.FileCommitCommitCommitter,
) -> json.Json {
  json.object(
    list.flatten([
      case value.date {
        option.None -> []
        option.Some(x) -> [#("date", json.string(x))]
      },
      case value.email {
        option.None -> []
        option.Some(x) -> [#("email", json.string(x))]
      },
      case value.name {
        option.None -> []
        option.Some(x) -> [#("name", json.string(x))]
      },
    ]),
  )
}

pub fn encode_file_commit_commit_committer(
  value: types.FileCommitCommitCommitter,
) -> String {
  encode_file_commit_commit_committer_json(value) |> json.to_string()
}

pub fn encode_file_commit_commit_parents_json(
  value: List(types.FileCommitCommitParentsItem),
) -> json.Json {
  json.array(value, encode_file_commit_commit_parents_item_json)
}

pub fn encode_file_commit_commit_parents(
  value: List(types.FileCommitCommitParentsItem),
) -> String {
  encode_file_commit_commit_parents_json(value) |> json.to_string()
}

pub fn encode_file_commit_commit_parents_item_json(
  value: types.FileCommitCommitParentsItem,
) -> json.Json {
  json.object(
    list.flatten([
      case value.html_url {
        option.None -> []
        option.Some(x) -> [#("html_url", json.string(x))]
      },
      case value.sha {
        option.None -> []
        option.Some(x) -> [#("sha", json.string(x))]
      },
      case value.url {
        option.None -> []
        option.Some(x) -> [#("url", json.string(x))]
      },
    ]),
  )
}

pub fn encode_file_commit_commit_parents_item(
  value: types.FileCommitCommitParentsItem,
) -> String {
  encode_file_commit_commit_parents_item_json(value) |> json.to_string()
}

pub fn encode_file_commit_commit_tree_json(
  value: types.FileCommitCommitTree,
) -> json.Json {
  json.object(
    list.flatten([
      case value.sha {
        option.None -> []
        option.Some(x) -> [#("sha", json.string(x))]
      },
      case value.url {
        option.None -> []
        option.Some(x) -> [#("url", json.string(x))]
      },
    ]),
  )
}

pub fn encode_file_commit_commit_tree(
  value: types.FileCommitCommitTree,
) -> String {
  encode_file_commit_commit_tree_json(value) |> json.to_string()
}

pub fn encode_file_commit_commit_verification_json(
  value: types.FileCommitCommitVerification,
) -> json.Json {
  json.object(
    list.flatten([
      [#("payload", json.nullable(value.payload, json.string))],
      case value.reason {
        option.None -> []
        option.Some(x) -> [#("reason", json.string(x))]
      },
      [#("signature", json.nullable(value.signature, json.string))],
      case value.verified {
        option.None -> []
        option.Some(x) -> [#("verified", json.bool(x))]
      },
      [#("verified_at", json.nullable(value.verified_at, json.string))],
    ]),
  )
}

pub fn encode_file_commit_commit_verification(
  value: types.FileCommitCommitVerification,
) -> String {
  encode_file_commit_commit_verification_json(value) |> json.to_string()
}

pub fn encode_file_commit_content_json(
  value: types.FileCommitContent,
) -> json.Json {
  json.object(
    list.flatten([
      case value.links {
        option.None -> []
        option.Some(x) -> [
          #("_links", encode_file_commit_content_links_json(x)),
        ]
      },
      case value.download_url {
        option.None -> []
        option.Some(x) -> [#("download_url", json.string(x))]
      },
      case value.git_url {
        option.None -> []
        option.Some(x) -> [#("git_url", json.string(x))]
      },
      case value.html_url {
        option.None -> []
        option.Some(x) -> [#("html_url", json.string(x))]
      },
      case value.name {
        option.None -> []
        option.Some(x) -> [#("name", json.string(x))]
      },
      case value.path {
        option.None -> []
        option.Some(x) -> [#("path", json.string(x))]
      },
      case value.sha {
        option.None -> []
        option.Some(x) -> [#("sha", json.string(x))]
      },
      case value.size {
        option.None -> []
        option.Some(x) -> [#("size", json.int(x))]
      },
      case value.type_ {
        option.None -> []
        option.Some(x) -> [#("type", json.string(x))]
      },
      case value.url {
        option.None -> []
        option.Some(x) -> [#("url", json.string(x))]
      },
    ]),
  )
}

pub fn encode_file_commit_content(value: types.FileCommitContent) -> String {
  encode_file_commit_content_json(value) |> json.to_string()
}

pub fn encode_file_commit_content_links_json(
  value: types.FileCommitContentLinks,
) -> json.Json {
  json.object(
    list.flatten([
      case value.git {
        option.None -> []
        option.Some(x) -> [#("git", json.string(x))]
      },
      case value.html {
        option.None -> []
        option.Some(x) -> [#("html", json.string(x))]
      },
      case value.self {
        option.None -> []
        option.Some(x) -> [#("self", json.string(x))]
      },
    ]),
  )
}

pub fn encode_file_commit_content_links(
  value: types.FileCommitContentLinks,
) -> String {
  encode_file_commit_content_links_json(value) |> json.to_string()
}

pub fn encode_integration_owner_json(
  value: types.IntegrationOwner,
) -> json.Json {
  case value {
    types.IntegrationOwnerSimpleUser(inner) -> encode_simple_user_json(inner)
    types.IntegrationOwnerEnterprise(inner) -> encode_enterprise_json(inner)
  }
}

pub fn encode_integration_owner(value: types.IntegrationOwner) -> String {
  encode_integration_owner_json(value) |> json.to_string()
}

pub fn encode_integration_permissions_json(
  value: types.IntegrationPermissions,
) -> json.Json {
  let base_props =
    list.flatten([
      case value.checks {
        option.None -> []
        option.Some(x) -> [#("checks", json.string(x))]
      },
      case value.contents {
        option.None -> []
        option.Some(x) -> [#("contents", json.string(x))]
      },
      case value.deployments {
        option.None -> []
        option.Some(x) -> [#("deployments", json.string(x))]
      },
      case value.issues {
        option.None -> []
        option.Some(x) -> [#("issues", json.string(x))]
      },
      case value.metadata {
        option.None -> []
        option.Some(x) -> [#("metadata", json.string(x))]
      },
    ])
  let extra_props =
    dict.to_list(value.additional_properties)
    |> list.map(fn(entry) {
      let #(k, v) = entry
      #(k, json.string(v))
    })
  json.object(list.append(base_props, extra_props))
}

pub fn encode_integration_permissions(
  value: types.IntegrationPermissions,
) -> String {
  encode_integration_permissions_json(value) |> json.to_string()
}

pub fn encode_issue_comment_minimized2_json(
  value: types.IssueCommentMinimized2,
) -> json.Json {
  case value.issue_comment_minimized {
    option.Some(v) -> encode_issue_comment_minimized_json(v)
    option.None -> json.null()
  }
}

pub fn encode_issue_comment_minimized2(
  value: types.IssueCommentMinimized2,
) -> String {
  encode_issue_comment_minimized2_json(value) |> json.to_string()
}

pub fn encode_issue_comment_performed_via_github_app_json(
  value: types.IssueCommentPerformedViaGithubApp,
) -> json.Json {
  case value.integration {
    option.Some(v) -> encode_integration_json(v)
    option.None -> json.null()
  }
}

pub fn encode_issue_comment_performed_via_github_app(
  value: types.IssueCommentPerformedViaGithubApp,
) -> String {
  encode_issue_comment_performed_via_github_app_json(value) |> json.to_string()
}

pub fn encode_issue_comment_pin_json(
  value: types.IssueCommentPin,
) -> json.Json {
  case value.pinned_issue_comment {
    option.Some(v) -> encode_pinned_issue_comment_json(v)
    option.None -> json.null()
  }
}

pub fn encode_issue_comment_pin(value: types.IssueCommentPin) -> String {
  encode_issue_comment_pin_json(value) |> json.to_string()
}

pub fn encode_issue_comment_user_json(
  value: types.IssueCommentUser,
) -> json.Json {
  case value.simple_user {
    option.Some(v) -> encode_simple_user_json(v)
    option.None -> json.null()
  }
}

pub fn encode_issue_comment_user(value: types.IssueCommentUser) -> String {
  encode_issue_comment_user_json(value) |> json.to_string()
}

pub fn encode_issues_create_comment_request_json(
  value: types.IssuesCreateCommentRequest,
) -> json.Json {
  json.object([#("body", json.string(value.body))])
}

pub fn encode_issues_create_comment_request(
  value: types.IssuesCreateCommentRequest,
) -> String {
  encode_issues_create_comment_request_json(value) |> json.to_string()
}

pub fn encode_issues_update_comment_request_json(
  value: types.IssuesUpdateCommentRequest,
) -> json.Json {
  json.object([#("body", json.string(value.body))])
}

pub fn encode_issues_update_comment_request(
  value: types.IssuesUpdateCommentRequest,
) -> String {
  encode_issues_update_comment_request_json(value) |> json.to_string()
}

pub fn encode_pinned_issue_comment_pinned_by_json(
  value: types.PinnedIssueCommentPinnedBy,
) -> json.Json {
  case value.simple_user {
    option.Some(v) -> encode_simple_user_json(v)
    option.None -> json.null()
  }
}

pub fn encode_pinned_issue_comment_pinned_by(
  value: types.PinnedIssueCommentPinnedBy,
) -> String {
  encode_pinned_issue_comment_pinned_by_json(value) |> json.to_string()
}

pub fn encode_repos_compare_commits_response_service_unavailable_json(
  value: types.ReposCompareCommitsResponseServiceUnavailable,
) -> json.Json {
  json.object(
    list.flatten([
      case value.code {
        option.None -> []
        option.Some(x) -> [#("code", json.string(x))]
      },
      case value.documentation_url {
        option.None -> []
        option.Some(x) -> [#("documentation_url", json.string(x))]
      },
      case value.message {
        option.None -> []
        option.Some(x) -> [#("message", json.string(x))]
      },
    ]),
  )
}

pub fn encode_repos_compare_commits_response_service_unavailable(
  value: types.ReposCompareCommitsResponseServiceUnavailable,
) -> String {
  encode_repos_compare_commits_response_service_unavailable_json(value)
  |> json.to_string()
}

pub fn encode_repos_create_or_update_file_contents_request_json(
  value: types.ReposCreateOrUpdateFileContentsRequest,
) -> json.Json {
  json.object(
    list.flatten([
      case value.author {
        option.None -> []
        option.Some(x) -> [
          #(
            "author",
            encode_repos_create_or_update_file_contents_request_author_json(x),
          ),
        ]
      },
      case value.branch {
        option.None -> []
        option.Some(x) -> [#("branch", json.string(x))]
      },
      case value.committer {
        option.None -> []
        option.Some(x) -> [
          #(
            "committer",
            encode_repos_create_or_update_file_contents_request_committer_json(
              x,
            ),
          ),
        ]
      },
      [#("content", json.string(value.content))],
      [#("message", json.string(value.message))],
      case value.sha {
        option.None -> []
        option.Some(x) -> [#("sha", json.string(x))]
      },
    ]),
  )
}

pub fn encode_repos_create_or_update_file_contents_request(
  value: types.ReposCreateOrUpdateFileContentsRequest,
) -> String {
  encode_repos_create_or_update_file_contents_request_json(value)
  |> json.to_string()
}

pub fn encode_repos_create_or_update_file_contents_request_author_json(
  value: types.ReposCreateOrUpdateFileContentsRequestAuthor,
) -> json.Json {
  json.object(
    list.flatten([
      case value.date {
        option.None -> []
        option.Some(x) -> [#("date", json.string(x))]
      },
      [#("email", json.string(value.email))],
      [#("name", json.string(value.name))],
    ]),
  )
}

pub fn encode_repos_create_or_update_file_contents_request_author(
  value: types.ReposCreateOrUpdateFileContentsRequestAuthor,
) -> String {
  encode_repos_create_or_update_file_contents_request_author_json(value)
  |> json.to_string()
}

pub fn encode_repos_create_or_update_file_contents_request_committer_json(
  value: types.ReposCreateOrUpdateFileContentsRequestCommitter,
) -> json.Json {
  json.object(
    list.flatten([
      case value.date {
        option.None -> []
        option.Some(x) -> [#("date", json.string(x))]
      },
      [#("email", json.string(value.email))],
      [#("name", json.string(value.name))],
    ]),
  )
}

pub fn encode_repos_create_or_update_file_contents_request_committer(
  value: types.ReposCreateOrUpdateFileContentsRequestCommitter,
) -> String {
  encode_repos_create_or_update_file_contents_request_committer_json(value)
  |> json.to_string()
}

pub fn encode_repos_create_or_update_file_contents_response_conflict_json(
  value: types.ReposCreateOrUpdateFileContentsResponseConflict,
) -> json.Json {
  case value {
    types.ReposCreateOrUpdateFileContentsResponseConflictBasicError(inner) ->
      encode_basic_error_json(inner)
    types.ReposCreateOrUpdateFileContentsResponseConflictRepositoryRuleViolationError(
      inner,
    ) -> encode_repository_rule_violation_error_json(inner)
  }
}

pub fn encode_repos_create_or_update_file_contents_response_conflict(
  value: types.ReposCreateOrUpdateFileContentsResponseConflict,
) -> String {
  encode_repos_create_or_update_file_contents_response_conflict_json(value)
  |> json.to_string()
}

pub fn encode_repos_delete_file_request_json(
  value: types.ReposDeleteFileRequest,
) -> json.Json {
  json.object(
    list.flatten([
      case value.author {
        option.None -> []
        option.Some(x) -> [
          #("author", encode_repos_delete_file_request_author_json(x)),
        ]
      },
      case value.branch {
        option.None -> []
        option.Some(x) -> [#("branch", json.string(x))]
      },
      case value.committer {
        option.None -> []
        option.Some(x) -> [
          #("committer", encode_repos_delete_file_request_committer_json(x)),
        ]
      },
      [#("message", json.string(value.message))],
      [#("sha", json.string(value.sha))],
    ]),
  )
}

pub fn encode_repos_delete_file_request(
  value: types.ReposDeleteFileRequest,
) -> String {
  encode_repos_delete_file_request_json(value) |> json.to_string()
}

pub fn encode_repos_delete_file_request_author_json(
  value: types.ReposDeleteFileRequestAuthor,
) -> json.Json {
  json.object(
    list.flatten([
      case value.email {
        option.None -> []
        option.Some(x) -> [#("email", json.string(x))]
      },
      case value.name {
        option.None -> []
        option.Some(x) -> [#("name", json.string(x))]
      },
    ]),
  )
}

pub fn encode_repos_delete_file_request_author(
  value: types.ReposDeleteFileRequestAuthor,
) -> String {
  encode_repos_delete_file_request_author_json(value) |> json.to_string()
}

pub fn encode_repos_delete_file_request_committer_json(
  value: types.ReposDeleteFileRequestCommitter,
) -> json.Json {
  json.object(
    list.flatten([
      case value.email {
        option.None -> []
        option.Some(x) -> [#("email", json.string(x))]
      },
      case value.name {
        option.None -> []
        option.Some(x) -> [#("name", json.string(x))]
      },
    ]),
  )
}

pub fn encode_repos_delete_file_request_committer(
  value: types.ReposDeleteFileRequestCommitter,
) -> String {
  encode_repos_delete_file_request_committer_json(value) |> json.to_string()
}

pub fn encode_repos_delete_file_response_service_unavailable_json(
  value: types.ReposDeleteFileResponseServiceUnavailable,
) -> json.Json {
  json.object(
    list.flatten([
      case value.code {
        option.None -> []
        option.Some(x) -> [#("code", json.string(x))]
      },
      case value.documentation_url {
        option.None -> []
        option.Some(x) -> [#("documentation_url", json.string(x))]
      },
      case value.message {
        option.None -> []
        option.Some(x) -> [#("message", json.string(x))]
      },
    ]),
  )
}

pub fn encode_repos_delete_file_response_service_unavailable(
  value: types.ReposDeleteFileResponseServiceUnavailable,
) -> String {
  encode_repos_delete_file_response_service_unavailable_json(value)
  |> json.to_string()
}

pub fn encode_repos_get_content_response_ok_json(
  value: types.ReposGetContentResponseOk,
) -> json.Json {
  case value {
    types.ReposGetContentResponseOkContentDirectory(inner) ->
      encode_content_directory_json(inner)
    types.ReposGetContentResponseOkContentFile(inner) ->
      encode_content_file_json(inner)
    types.ReposGetContentResponseOkContentSymlink(inner) ->
      encode_content_symlink_json(inner)
    types.ReposGetContentResponseOkContentSubmodule(inner) ->
      encode_content_submodule_json(inner)
  }
}

pub fn encode_repos_get_content_response_ok(
  value: types.ReposGetContentResponseOk,
) -> String {
  encode_repos_get_content_response_ok_json(value) |> json.to_string()
}

pub fn encode_repository_rule_violation_error_metadata_json(
  value: types.RepositoryRuleViolationErrorMetadata,
) -> json.Json {
  json.object(
    list.flatten([
      case value.secret_scanning {
        option.None -> []
        option.Some(x) -> [
          #(
            "secret_scanning",
            encode_repository_rule_violation_error_metadata_secret_scanning_json(
              x,
            ),
          ),
        ]
      },
    ]),
  )
}

pub fn encode_repository_rule_violation_error_metadata(
  value: types.RepositoryRuleViolationErrorMetadata,
) -> String {
  encode_repository_rule_violation_error_metadata_json(value)
  |> json.to_string()
}

pub fn encode_repository_rule_violation_error_metadata_secret_scanning_json(
  value: types.RepositoryRuleViolationErrorMetadataSecretScanning,
) -> json.Json {
  json.object(
    list.flatten([
      case value.bypass_placeholders {
        option.None -> []
        option.Some(x) -> [
          #(
            "bypass_placeholders",
            encode_repository_rule_violation_error_metadata_secret_scanning_bypass_placeholders_json(
              x,
            ),
          ),
        ]
      },
    ]),
  )
}

pub fn encode_repository_rule_violation_error_metadata_secret_scanning(
  value: types.RepositoryRuleViolationErrorMetadataSecretScanning,
) -> String {
  encode_repository_rule_violation_error_metadata_secret_scanning_json(value)
  |> json.to_string()
}

pub fn encode_repository_rule_violation_error_metadata_secret_scanning_bypass_placeholders_json(
  value: List(
    types.RepositoryRuleViolationErrorMetadataSecretScanningBypassPlaceholdersItem,
  ),
) -> json.Json {
  json.array(
    value,
    encode_repository_rule_violation_error_metadata_secret_scanning_bypass_placeholders_item_json,
  )
}

pub fn encode_repository_rule_violation_error_metadata_secret_scanning_bypass_placeholders(
  value: List(
    types.RepositoryRuleViolationErrorMetadataSecretScanningBypassPlaceholdersItem,
  ),
) -> String {
  encode_repository_rule_violation_error_metadata_secret_scanning_bypass_placeholders_json(
    value,
  )
  |> json.to_string()
}

pub fn encode_repository_rule_violation_error_metadata_secret_scanning_bypass_placeholders_item_json(
  value: types.RepositoryRuleViolationErrorMetadataSecretScanningBypassPlaceholdersItem,
) -> json.Json {
  json.object(
    list.flatten([
      case value.placeholder_id {
        option.None -> []
        option.Some(x) -> [
          #(
            "placeholder_id",
            encode_secret_scanning_push_protection_bypass_placeholder_id_json(x),
          ),
        ]
      },
      case value.token_type {
        option.None -> []
        option.Some(x) -> [#("token_type", json.string(x))]
      },
    ]),
  )
}

pub fn encode_repository_rule_violation_error_metadata_secret_scanning_bypass_placeholders_item(
  value: types.RepositoryRuleViolationErrorMetadataSecretScanningBypassPlaceholdersItem,
) -> String {
  encode_repository_rule_violation_error_metadata_secret_scanning_bypass_placeholders_item_json(
    value,
  )
  |> json.to_string()
}

pub fn encode_validation_error_errors_json(
  value: List(types.ValidationErrorErrorsItem),
) -> json.Json {
  json.array(value, encode_validation_error_errors_item_json)
}

pub fn encode_validation_error_errors(
  value: List(types.ValidationErrorErrorsItem),
) -> String {
  encode_validation_error_errors_json(value) |> json.to_string()
}

pub fn encode_validation_error_errors_item_json(
  value: types.ValidationErrorErrorsItem,
) -> json.Json {
  json.object(
    list.flatten([
      [#("code", json.string(value.code))],
      case value.field {
        option.None -> []
        option.Some(x) -> [#("field", json.string(x))]
      },
      case value.index {
        option.None -> []
        option.Some(x) -> [#("index", json.int(x))]
      },
      case value.message {
        option.None -> []
        option.Some(x) -> [#("message", json.string(x))]
      },
      case value.resource {
        option.None -> []
        option.Some(x) -> [#("resource", json.string(x))]
      },
      case value.value {
        option.None -> []
        option.Some(x) -> [
          #("value", encode_validation_error_errors_item_value_json(x)),
        ]
      },
    ]),
  )
}

pub fn encode_validation_error_errors_item(
  value: types.ValidationErrorErrorsItem,
) -> String {
  encode_validation_error_errors_item_json(value) |> json.to_string()
}

pub fn encode_validation_error_errors_item_value_json(
  value: types.ValidationErrorErrorsItemValue,
) -> json.Json {
  case value {
    types.ValidationErrorErrorsItemValueValidationErrorErrorsItemValueVariant0(
      inner,
    ) -> encode_validation_error_errors_item_value_variant0_json(inner)
    types.ValidationErrorErrorsItemValueValidationErrorErrorsItemValueVariant1(
      inner,
    ) -> encode_validation_error_errors_item_value_variant1_json(inner)
    types.ValidationErrorErrorsItemValueValidationErrorErrorsItemValueVariant2(
      inner,
    ) -> encode_validation_error_errors_item_value_variant2_json(inner)
  }
}

pub fn encode_validation_error_errors_item_value(
  value: types.ValidationErrorErrorsItemValue,
) -> String {
  encode_validation_error_errors_item_value_json(value) |> json.to_string()
}

pub fn encode_validation_error_errors_item_value_variant0_json(
  value: Option(String),
) -> json.Json {
  json.nullable(value, json.string)
}

pub fn encode_validation_error_errors_item_value_variant0(
  value: Option(String),
) -> String {
  encode_validation_error_errors_item_value_variant0_json(value)
  |> json.to_string()
}

pub fn encode_validation_error_errors_item_value_variant1_json(
  value: Option(Int),
) -> json.Json {
  json.nullable(value, json.int)
}

pub fn encode_validation_error_errors_item_value_variant1(
  value: Option(Int),
) -> String {
  encode_validation_error_errors_item_value_variant1_json(value)
  |> json.to_string()
}

pub fn encode_validation_error_errors_item_value_variant2_json(
  value: Option(List(String)),
) -> json.Json {
  json.nullable(value, fn(value) { json.array(value, json.string) })
}

pub fn encode_validation_error_errors_item_value_variant2(
  value: Option(List(String)),
) -> String {
  encode_validation_error_errors_item_value_variant2_json(value)
  |> json.to_string()
}

pub fn encode_author_association_json(
  value: types.AuthorAssociation,
) -> json.Json {
  let str = case value {
    types.AuthorAssociationCOLLABORATOR -> "COLLABORATOR"
    types.AuthorAssociationCONTRIBUTOR -> "CONTRIBUTOR"
    types.AuthorAssociationFIRSTTIMER -> "FIRST_TIMER"
    types.AuthorAssociationFIRSTTIMECONTRIBUTOR -> "FIRST_TIME_CONTRIBUTOR"
    types.AuthorAssociationMANNEQUIN -> "MANNEQUIN"
    types.AuthorAssociationMEMBER -> "MEMBER"
    types.AuthorAssociationNONE -> "NONE"
    types.AuthorAssociationOWNER -> "OWNER"
  }
  json.string(str)
}

pub fn encode_author_association(value: types.AuthorAssociation) -> String {
  encode_author_association_json(value) |> json.to_string()
}

pub fn encode_author_association_to_string(
  value: types.AuthorAssociation,
) -> String {
  case value {
    types.AuthorAssociationCOLLABORATOR -> "COLLABORATOR"
    types.AuthorAssociationCONTRIBUTOR -> "CONTRIBUTOR"
    types.AuthorAssociationFIRSTTIMER -> "FIRST_TIMER"
    types.AuthorAssociationFIRSTTIMECONTRIBUTOR -> "FIRST_TIME_CONTRIBUTOR"
    types.AuthorAssociationMANNEQUIN -> "MANNEQUIN"
    types.AuthorAssociationMEMBER -> "MEMBER"
    types.AuthorAssociationNONE -> "NONE"
    types.AuthorAssociationOWNER -> "OWNER"
  }
}

pub fn encode_basic_error_json(value: types.BasicError) -> json.Json {
  json.object(
    list.flatten([
      case value.documentation_url {
        option.None -> []
        option.Some(x) -> [#("documentation_url", json.string(x))]
      },
      case value.message {
        option.None -> []
        option.Some(x) -> [#("message", json.string(x))]
      },
      case value.status {
        option.None -> []
        option.Some(x) -> [#("status", json.string(x))]
      },
      case value.url {
        option.None -> []
        option.Some(x) -> [#("url", json.string(x))]
      },
    ]),
  )
}

pub fn encode_basic_error(value: types.BasicError) -> String {
  encode_basic_error_json(value) |> json.to_string()
}

pub fn encode_commit_json(value: types.Commit) -> json.Json {
  json.object(
    list.flatten([
      [#("author", json.nullable(value.author, encode_commit_author_json))],
      [#("comments_url", json.string(value.comments_url))],
      [#("commit", encode_commit_commit_json(value.commit))],
      [
        #(
          "committer",
          json.nullable(value.committer, encode_commit_committer_json),
        ),
      ],
      case value.files {
        option.None -> []
        option.Some(x) -> [#("files", json.array(x, encode_diff_entry_json))]
      },
      [#("html_url", json.string(value.html_url))],
      [#("node_id", json.string(value.node_id))],
      [#("parents", encode_commit_parents_json(value.parents))],
      [#("sha", json.string(value.sha))],
      case value.stats {
        option.None -> []
        option.Some(x) -> [#("stats", encode_commit_stats_json(x))]
      },
      [#("url", json.string(value.url))],
    ]),
  )
}

pub fn encode_commit(value: types.Commit) -> String {
  encode_commit_json(value) |> json.to_string()
}

pub fn encode_commit_comparison_json(
  value: types.CommitComparison,
) -> json.Json {
  json.object(
    list.flatten([
      [#("ahead_by", json.int(value.ahead_by))],
      [#("base_commit", encode_commit_json(value.base_commit))],
      [#("behind_by", json.int(value.behind_by))],
      [#("commits", json.array(value.commits, encode_commit_json))],
      [#("diff_url", json.string(value.diff_url))],
      case value.files {
        option.None -> []
        option.Some(x) -> [#("files", json.array(x, encode_diff_entry_json))]
      },
      [#("html_url", json.string(value.html_url))],
      [#("merge_base_commit", encode_commit_json(value.merge_base_commit))],
      [#("patch_url", json.string(value.patch_url))],
      [#("permalink_url", json.string(value.permalink_url))],
      [#("status", encode_commit_comparison_status_json(value.status))],
      [#("total_commits", json.int(value.total_commits))],
      [#("url", json.string(value.url))],
    ]),
  )
}

pub fn encode_commit_comparison(value: types.CommitComparison) -> String {
  encode_commit_comparison_json(value) |> json.to_string()
}

pub fn encode_content_directory_json(
  value: List(types.ContentDirectoryItem),
) -> json.Json {
  json.array(value, encode_content_directory_item_json)
}

pub fn encode_content_directory(
  value: List(types.ContentDirectoryItem),
) -> String {
  encode_content_directory_json(value) |> json.to_string()
}

pub fn encode_content_file_json(value: types.ContentFile) -> json.Json {
  json.object(
    list.flatten([
      [#("_links", encode_content_file_links_json(value.links))],
      [#("content", json.string(value.content))],
      [#("download_url", json.nullable(value.download_url, json.string))],
      [#("encoding", json.string(value.encoding))],
      [#("git_url", json.nullable(value.git_url, json.string))],
      [#("html_url", json.nullable(value.html_url, json.string))],
      [#("name", json.string(value.name))],
      [#("path", json.string(value.path))],
      [#("sha", json.string(value.sha))],
      [#("size", json.int(value.size))],
      case value.submodule_git_url {
        option.None -> []
        option.Some(x) -> [#("submodule_git_url", json.string(x))]
      },
      case value.target {
        option.None -> []
        option.Some(x) -> [#("target", json.string(x))]
      },
      [#("type", json.string("file"))],
      [#("url", json.string(value.url))],
    ]),
  )
}

pub fn encode_content_file(value: types.ContentFile) -> String {
  encode_content_file_json(value) |> json.to_string()
}

pub fn encode_content_submodule_json(
  value: types.ContentSubmodule,
) -> json.Json {
  json.object([
    #("_links", encode_content_submodule_links_json(value.links)),
    #("download_url", json.nullable(value.download_url, json.string)),
    #("git_url", json.nullable(value.git_url, json.string)),
    #("html_url", json.nullable(value.html_url, json.string)),
    #("name", json.string(value.name)),
    #("path", json.string(value.path)),
    #("sha", json.string(value.sha)),
    #("size", json.int(value.size)),
    #("submodule_git_url", json.string(value.submodule_git_url)),
    #("type", json.string("submodule")),
    #("url", json.string(value.url)),
  ])
}

pub fn encode_content_submodule(value: types.ContentSubmodule) -> String {
  encode_content_submodule_json(value) |> json.to_string()
}

pub fn encode_content_symlink_json(value: types.ContentSymlink) -> json.Json {
  json.object([
    #("_links", encode_content_symlink_links_json(value.links)),
    #("download_url", json.nullable(value.download_url, json.string)),
    #("git_url", json.nullable(value.git_url, json.string)),
    #("html_url", json.nullable(value.html_url, json.string)),
    #("name", json.string(value.name)),
    #("path", json.string(value.path)),
    #("sha", json.string(value.sha)),
    #("size", json.int(value.size)),
    #("target", json.string(value.target)),
    #("type", json.string("symlink")),
    #("url", json.string(value.url)),
  ])
}

pub fn encode_content_symlink(value: types.ContentSymlink) -> String {
  encode_content_symlink_json(value) |> json.to_string()
}

pub fn encode_content_tree_json(value: types.ContentTree) -> json.Json {
  json.object(
    list.flatten([
      [#("_links", encode_content_tree_links_json(value.links))],
      case value.content {
        option.None -> []
        option.Some(x) -> [#("content", json.string(x))]
      },
      [#("download_url", json.nullable(value.download_url, json.string))],
      case value.encoding {
        option.None -> []
        option.Some(x) -> [#("encoding", json.string(x))]
      },
      case value.entries {
        option.None -> []
        option.Some(x) -> [#("entries", encode_content_tree_entries_json(x))]
      },
      [#("git_url", json.nullable(value.git_url, json.string))],
      [#("html_url", json.nullable(value.html_url, json.string))],
      [#("name", json.string(value.name))],
      [#("path", json.string(value.path))],
      [#("sha", json.string(value.sha))],
      [#("size", json.int(value.size))],
      [#("type", json.string(value.type_))],
      [#("url", json.string(value.url))],
    ]),
  )
}

pub fn encode_content_tree(value: types.ContentTree) -> String {
  encode_content_tree_json(value) |> json.to_string()
}

pub fn encode_diff_entry_json(value: types.DiffEntry) -> json.Json {
  json.object(
    list.flatten([
      [#("additions", json.int(value.additions))],
      [#("blob_url", json.string(value.blob_url))],
      [#("changes", json.int(value.changes))],
      [#("contents_url", json.string(value.contents_url))],
      [#("deletions", json.int(value.deletions))],
      [#("filename", json.string(value.filename))],
      case value.patch {
        option.None -> []
        option.Some(x) -> [#("patch", json.string(x))]
      },
      case value.previous_filename {
        option.None -> []
        option.Some(x) -> [#("previous_filename", json.string(x))]
      },
      [#("raw_url", json.string(value.raw_url))],
      [#("sha", json.nullable(value.sha, json.string))],
      [#("status", encode_diff_entry_status_json(value.status))],
    ]),
  )
}

pub fn encode_diff_entry(value: types.DiffEntry) -> String {
  encode_diff_entry_json(value) |> json.to_string()
}

pub fn encode_empty_object_json(_value: types.EmptyObject) -> json.Json {
  json.object([])
}

pub fn encode_empty_object(value: types.EmptyObject) -> String {
  encode_empty_object_json(value) |> json.to_string()
}

pub fn encode_enterprise_json(value: types.Enterprise) -> json.Json {
  json.object([
    #("avatar_url", json.string(value.avatar_url)),
    #("created_at", json.nullable(value.created_at, json.string)),
    #("description", json.nullable(value.description, json.string)),
    #("html_url", json.string(value.html_url)),
    #("id", json.int(value.id)),
    #("name", json.string(value.name)),
    #("node_id", json.string(value.node_id)),
    #("slug", json.string(value.slug)),
    #("updated_at", json.nullable(value.updated_at, json.string)),
    #("website_url", json.nullable(value.website_url, json.string)),
  ])
}

pub fn encode_enterprise(value: types.Enterprise) -> String {
  encode_enterprise_json(value) |> json.to_string()
}

pub fn encode_file_commit_json(value: types.FileCommit) -> json.Json {
  json.object([
    #("commit", encode_file_commit_commit_json(value.commit)),
    #("content", json.nullable(value.content, encode_file_commit_content_json)),
  ])
}

pub fn encode_file_commit(value: types.FileCommit) -> String {
  encode_file_commit_json(value) |> json.to_string()
}

pub fn encode_git_user_json(value: types.GitUser) -> json.Json {
  json.object(
    list.flatten([
      case value.date {
        option.None -> []
        option.Some(x) -> [#("date", json.string(x))]
      },
      case value.email {
        option.None -> []
        option.Some(x) -> [#("email", json.string(x))]
      },
      case value.name {
        option.None -> []
        option.Some(x) -> [#("name", json.string(x))]
      },
    ]),
  )
}

pub fn encode_git_user(value: types.GitUser) -> String {
  encode_git_user_json(value) |> json.to_string()
}

pub fn encode_integration_json(value: types.Integration) -> json.Json {
  json.object(
    list.flatten([
      case value.client_id {
        option.None -> []
        option.Some(x) -> [#("client_id", json.string(x))]
      },
      [#("created_at", json.string(value.created_at))],
      [#("description", json.nullable(value.description, json.string))],
      [#("events", json.array(value.events, json.string))],
      [#("external_url", json.string(value.external_url))],
      [#("html_url", json.string(value.html_url))],
      [#("id", json.int(value.id))],
      case value.installations_count {
        option.None -> []
        option.Some(x) -> [#("installations_count", json.int(x))]
      },
      [#("name", json.string(value.name))],
      [#("node_id", json.string(value.node_id))],
      [#("owner", encode_integration_owner_json(value.owner))],
      [#("permissions", encode_integration_permissions_json(value.permissions))],
      case value.slug {
        option.None -> []
        option.Some(x) -> [#("slug", json.string(x))]
      },
      [#("updated_at", json.string(value.updated_at))],
    ]),
  )
}

pub fn encode_integration(value: types.Integration) -> String {
  encode_integration_json(value) |> json.to_string()
}

pub fn encode_issue_comment_json(value: types.IssueComment) -> json.Json {
  json.object(
    list.flatten([
      case value.author_association {
        option.None -> []
        option.Some(x) -> [
          #("author_association", encode_author_association_json(x)),
        ]
      },
      case value.body {
        option.None -> []
        option.Some(x) -> [#("body", json.string(x))]
      },
      case value.body_html {
        option.None -> []
        option.Some(x) -> [#("body_html", json.string(x))]
      },
      case value.body_text {
        option.None -> []
        option.Some(x) -> [#("body_text", json.string(x))]
      },
      [#("created_at", json.string(value.created_at))],
      [#("html_url", json.string(value.html_url))],
      [#("id", json.int(value.id))],
      [#("issue_url", json.string(value.issue_url))],
      [
        #(
          "minimized",
          json.nullable(value.minimized, encode_issue_comment_minimized2_json),
        ),
      ],
      [#("node_id", json.string(value.node_id))],
      [
        #(
          "performed_via_github_app",
          json.nullable(
            value.performed_via_github_app,
            encode_issue_comment_performed_via_github_app_json,
          ),
        ),
      ],
      [#("pin", json.nullable(value.pin, encode_issue_comment_pin_json))],
      case value.reactions {
        option.None -> []
        option.Some(x) -> [#("reactions", encode_reaction_rollup_json(x))]
      },
      [#("updated_at", json.string(value.updated_at))],
      [#("url", json.string(value.url))],
      [#("user", json.nullable(value.user, encode_issue_comment_user_json))],
    ]),
  )
}

pub fn encode_issue_comment(value: types.IssueComment) -> String {
  encode_issue_comment_json(value) |> json.to_string()
}

pub fn encode_issue_comment_minimized_json(
  value: types.IssueCommentMinimized,
) -> json.Json {
  json.object([#("reason", json.nullable(value.reason, json.string))])
}

pub fn encode_issue_comment_minimized(
  value: types.IssueCommentMinimized,
) -> String {
  encode_issue_comment_minimized_json(value) |> json.to_string()
}

pub fn encode_pinned_issue_comment_json(
  value: types.PinnedIssueComment,
) -> json.Json {
  json.object([
    #("pinned_at", json.string(value.pinned_at)),
    #(
      "pinned_by",
      json.nullable(value.pinned_by, encode_pinned_issue_comment_pinned_by_json),
    ),
  ])
}

pub fn encode_pinned_issue_comment(value: types.PinnedIssueComment) -> String {
  encode_pinned_issue_comment_json(value) |> json.to_string()
}

pub fn encode_reaction_rollup_json(value: types.ReactionRollup) -> json.Json {
  json.object([
    #("+1", json.int(value.plus_1)),
    #("-1", json.int(value.minus_1)),
    #("confused", json.int(value.confused)),
    #("eyes", json.int(value.eyes)),
    #("heart", json.int(value.heart)),
    #("hooray", json.int(value.hooray)),
    #("laugh", json.int(value.laugh)),
    #("rocket", json.int(value.rocket)),
    #("total_count", json.int(value.total_count)),
    #("url", json.string(value.url)),
  ])
}

pub fn encode_reaction_rollup(value: types.ReactionRollup) -> String {
  encode_reaction_rollup_json(value) |> json.to_string()
}

pub fn encode_repository_rule_violation_error_json(
  value: types.RepositoryRuleViolationError,
) -> json.Json {
  json.object(
    list.flatten([
      case value.documentation_url {
        option.None -> []
        option.Some(x) -> [#("documentation_url", json.string(x))]
      },
      case value.message {
        option.None -> []
        option.Some(x) -> [#("message", json.string(x))]
      },
      case value.metadata {
        option.None -> []
        option.Some(x) -> [
          #("metadata", encode_repository_rule_violation_error_metadata_json(x)),
        ]
      },
      case value.status {
        option.None -> []
        option.Some(x) -> [#("status", json.string(x))]
      },
    ]),
  )
}

pub fn encode_repository_rule_violation_error(
  value: types.RepositoryRuleViolationError,
) -> String {
  encode_repository_rule_violation_error_json(value) |> json.to_string()
}

pub fn encode_secret_scanning_push_protection_bypass_placeholder_id_json(
  value: String,
) -> json.Json {
  json.string(value)
}

pub fn encode_secret_scanning_push_protection_bypass_placeholder_id(
  value: String,
) -> String {
  encode_secret_scanning_push_protection_bypass_placeholder_id_json(value)
  |> json.to_string()
}

pub fn encode_simple_user_json(value: types.SimpleUser) -> json.Json {
  json.object(
    list.flatten([
      [#("avatar_url", json.string(value.avatar_url))],
      [#("email", json.nullable(value.email, json.string))],
      [#("events_url", json.string(value.events_url))],
      [#("followers_url", json.string(value.followers_url))],
      [#("following_url", json.string(value.following_url))],
      [#("gists_url", json.string(value.gists_url))],
      [#("gravatar_id", json.nullable(value.gravatar_id, json.string))],
      [#("html_url", json.string(value.html_url))],
      [#("id", json.int(value.id))],
      [#("login", json.string(value.login))],
      [#("name", json.nullable(value.name, json.string))],
      [#("node_id", json.string(value.node_id))],
      [#("organizations_url", json.string(value.organizations_url))],
      [#("received_events_url", json.string(value.received_events_url))],
      [#("repos_url", json.string(value.repos_url))],
      [#("site_admin", json.bool(value.site_admin))],
      case value.starred_at {
        option.None -> []
        option.Some(x) -> [#("starred_at", json.string(x))]
      },
      [#("starred_url", json.string(value.starred_url))],
      [#("subscriptions_url", json.string(value.subscriptions_url))],
      [#("type", json.string(value.type_))],
      [#("url", json.string(value.url))],
      case value.user_view_type {
        option.None -> []
        option.Some(x) -> [#("user_view_type", json.string(x))]
      },
    ]),
  )
}

pub fn encode_simple_user(value: types.SimpleUser) -> String {
  encode_simple_user_json(value) |> json.to_string()
}

pub fn encode_validation_error_json(value: types.ValidationError) -> json.Json {
  json.object(
    list.flatten([
      [#("documentation_url", json.string(value.documentation_url))],
      case value.errors {
        option.None -> []
        option.Some(x) -> [#("errors", encode_validation_error_errors_json(x))]
      },
      [#("message", json.string(value.message))],
    ]),
  )
}

pub fn encode_validation_error(value: types.ValidationError) -> String {
  encode_validation_error_json(value) |> json.to_string()
}

pub fn encode_verification_json(value: types.Verification) -> json.Json {
  json.object([
    #("payload", json.nullable(value.payload, json.string)),
    #("reason", json.string(value.reason)),
    #("signature", json.nullable(value.signature, json.string)),
    #("verified", json.bool(value.verified)),
    #("verified_at", json.nullable(value.verified_at, json.string)),
  ])
}

pub fn encode_verification(value: types.Verification) -> String {
  encode_verification_json(value) |> json.to_string()
}
