// Code generated by oaspec v0.61.0. DO NOT EDIT.

import dco_check/internal/github/types
import gleam/option.{type Option}

pub type ReposCompareCommitsResponse {
  ReposCompareCommitsResponseOk(String)
  ReposCompareCommitsResponseNotFound(types.BasicError)
  ReposCompareCommitsResponseInternalServerError(types.BasicError)
  ReposCompareCommitsResponseServiceUnavailable(
    types.ReposCompareCommitsResponseServiceUnavailable,
  )
}

pub type IssuesGetCommentResponse {
  IssuesGetCommentResponseOk(types.IssueComment)
  IssuesGetCommentResponseNotFound(types.BasicError)
}

pub type IssuesDeleteCommentResponse {
  IssuesDeleteCommentResponseNoContent
}

pub type IssuesUpdateCommentResponse {
  IssuesUpdateCommentResponseOk(types.IssueComment)
  IssuesUpdateCommentResponseUnprocessableEntity(types.ValidationError)
}

pub type IssuesListCommentsResponse {
  IssuesListCommentsResponseOk(
    List(types.IssueComment),
    IssuesListCommentsResponseOkHeaders,
  )
  IssuesListCommentsResponseNotFound(types.BasicError)
  IssuesListCommentsResponseGone(types.BasicError)
}

pub type IssuesCreateCommentResponse {
  IssuesCreateCommentResponseCreated(
    types.IssueComment,
    IssuesCreateCommentResponseCreatedHeaders,
  )
  IssuesCreateCommentResponseForbidden(types.BasicError)
  IssuesCreateCommentResponseNotFound(types.BasicError)
  IssuesCreateCommentResponseGone(types.BasicError)
  IssuesCreateCommentResponseUnprocessableEntity(types.ValidationError)
}

pub type IssuesListCommentsResponseOkHeaders {
  IssuesListCommentsResponseOkHeaders(link: Option(String))
}

pub type IssuesCreateCommentResponseCreatedHeaders {
  IssuesCreateCommentResponseCreatedHeaders(location: Option(String))
}
