// Code generated by oaspec v0.69.0. DO NOT EDIT.

import gleam/dict.{type Dict}
import gleam/option.{type Option}

pub type ContentDirectoryItemType {
  ContentDirectoryItemTypeDir
  ContentDirectoryItemTypeFile
  ContentDirectoryItemTypeSubmodule
  ContentDirectoryItemTypeSymlink
}

pub type CommitComparisonStatus {
  CommitComparisonStatusDiverged
  CommitComparisonStatusAhead
  CommitComparisonStatusBehind
  CommitComparisonStatusIdentical
}

pub type DiffEntryStatus {
  DiffEntryStatusAdded
  DiffEntryStatusRemoved
  DiffEntryStatusModified
  DiffEntryStatusRenamed
  DiffEntryStatusCopied
  DiffEntryStatusChanged
  DiffEntryStatusUnchanged
}

pub type CommitAuthor {
  CommitAuthorSimpleUser(SimpleUser)
  CommitAuthorEmptyObject(EmptyObject)
}

pub type CommitCommit {
  CommitCommit(
    author: Option(CommitCommitAuthor),
    comment_count: Int,
    committer: Option(CommitCommitCommitter),
    message: String,
    tree: CommitCommitTree,
    url: String,
    verification: Option(Verification),
  )
}

pub type CommitCommitAuthor {
  CommitCommitAuthor(git_user: Option(GitUser))
}

pub type CommitCommitCommitter {
  CommitCommitCommitter(git_user: Option(GitUser))
}

pub type CommitCommitTree {
  CommitCommitTree(sha: String, url: String)
}

pub type CommitCommitter {
  CommitCommitterSimpleUser(SimpleUser)
  CommitCommitterEmptyObject(EmptyObject)
}

pub type CommitParents =
  List(CommitParentsItem)

pub type CommitParentsItem {
  CommitParentsItem(html_url: Option(String), sha: String, url: String)
}

pub type CommitStats {
  CommitStats(
    additions: Option(Int),
    deletions: Option(Int),
    total: Option(Int),
  )
}

pub type ContentDirectoryItem {
  ContentDirectoryItem(
    links: ContentDirectoryItemLinks,
    content: Option(String),
    download_url: Option(String),
    git_url: Option(String),
    html_url: Option(String),
    name: String,
    path: String,
    sha: String,
    size: Int,
    type_: ContentDirectoryItemType,
    url: String,
  )
}

pub type ContentDirectoryItemLinks {
  ContentDirectoryItemLinks(
    git: Option(String),
    html: Option(String),
    self: String,
  )
}

pub type ContentFileLinks {
  ContentFileLinks(git: Option(String), html: Option(String), self: String)
}

pub type ContentSubmoduleLinks {
  ContentSubmoduleLinks(git: Option(String), html: Option(String), self: String)
}

pub type ContentSymlinkLinks {
  ContentSymlinkLinks(git: Option(String), html: Option(String), self: String)
}

pub type ContentTreeEntries =
  List(ContentTreeEntriesItem)

pub type ContentTreeEntriesItem {
  ContentTreeEntriesItem(
    links: ContentTreeEntriesItemLinks,
    download_url: Option(String),
    git_url: Option(String),
    html_url: Option(String),
    name: String,
    path: String,
    sha: String,
    size: Int,
    type_: String,
    url: String,
  )
}

pub type ContentTreeEntriesItemLinks {
  ContentTreeEntriesItemLinks(
    git: Option(String),
    html: Option(String),
    self: String,
  )
}

pub type ContentTreeLinks {
  ContentTreeLinks(git: Option(String), html: Option(String), self: String)
}

pub type FileCommitCommit {
  FileCommitCommit(
    author: Option(FileCommitCommitAuthor),
    committer: Option(FileCommitCommitCommitter),
    html_url: Option(String),
    message: Option(String),
    node_id: Option(String),
    parents: Option(FileCommitCommitParents),
    sha: Option(String),
    tree: Option(FileCommitCommitTree),
    url: Option(String),
    verification: Option(FileCommitCommitVerification),
  )
}

pub type FileCommitCommitAuthor {
  FileCommitCommitAuthor(
    date: Option(String),
    email: Option(String),
    name: Option(String),
  )
}

pub type FileCommitCommitCommitter {
  FileCommitCommitCommitter(
    date: Option(String),
    email: Option(String),
    name: Option(String),
  )
}

pub type FileCommitCommitParents =
  List(FileCommitCommitParentsItem)

pub type FileCommitCommitParentsItem {
  FileCommitCommitParentsItem(
    html_url: Option(String),
    sha: Option(String),
    url: Option(String),
  )
}

pub type FileCommitCommitTree {
  FileCommitCommitTree(sha: Option(String), url: Option(String))
}

pub type FileCommitCommitVerification {
  FileCommitCommitVerification(
    payload: Option(String),
    reason: Option(String),
    signature: Option(String),
    verified: Option(Bool),
    verified_at: Option(String),
  )
}

pub type FileCommitContent {
  FileCommitContent(
    links: Option(FileCommitContentLinks),
    download_url: Option(String),
    git_url: Option(String),
    html_url: Option(String),
    name: Option(String),
    path: Option(String),
    sha: Option(String),
    size: Option(Int),
    type_: Option(String),
    url: Option(String),
  )
}

pub type FileCommitContentLinks {
  FileCommitContentLinks(
    git: Option(String),
    html: Option(String),
    self: Option(String),
  )
}

pub type IntegrationOwner {
  IntegrationOwnerSimpleUser(SimpleUser)
  IntegrationOwnerEnterprise(Enterprise)
}

/// The set of permissions for the GitHub app
pub type IntegrationPermissions {
  IntegrationPermissions(
    checks: Option(String),
    contents: Option(String),
    deployments: Option(String),
    issues: Option(String),
    metadata: Option(String),
    additional_properties: Dict(String, String),
  )
}

pub type IssueCommentMinimized2 {
  IssueCommentMinimized2(issue_comment_minimized: Option(IssueCommentMinimized))
}

pub type IssueCommentPerformedViaGithubApp {
  IssueCommentPerformedViaGithubApp(integration: Option(Integration))
}

pub type IssueCommentPin {
  IssueCommentPin(pinned_issue_comment: Option(PinnedIssueComment))
}

pub type IssueCommentUser {
  IssueCommentUser(simple_user: Option(SimpleUser))
}

pub type IssuesCreateCommentRequest {
  IssuesCreateCommentRequest(body: String)
}

pub type IssuesUpdateCommentRequest {
  IssuesUpdateCommentRequest(body: String)
}

pub type PinnedIssueCommentPinnedBy {
  PinnedIssueCommentPinnedBy(simple_user: Option(SimpleUser))
}

pub type ReposCompareCommitsResponseServiceUnavailable {
  ReposCompareCommitsResponseServiceUnavailable(
    code: Option(String),
    documentation_url: Option(String),
    message: Option(String),
  )
}

pub type ReposCreateOrUpdateFileContentsRequest {
  ReposCreateOrUpdateFileContentsRequest(
    author: Option(ReposCreateOrUpdateFileContentsRequestAuthor),
    branch: Option(String),
    committer: Option(ReposCreateOrUpdateFileContentsRequestCommitter),
    content: String,
    message: String,
    sha: Option(String),
  )
}

/// The author of the file. Default: The `committer` or the authenticated user if you omit `committer`.
pub type ReposCreateOrUpdateFileContentsRequestAuthor {
  ReposCreateOrUpdateFileContentsRequestAuthor(
    date: Option(String),
    email: String,
    name: String,
  )
}

/// The person that committed the file. Default: the authenticated user.
pub type ReposCreateOrUpdateFileContentsRequestCommitter {
  ReposCreateOrUpdateFileContentsRequestCommitter(
    date: Option(String),
    email: String,
    name: String,
  )
}

pub type ReposCreateOrUpdateFileContentsResponseConflict {
  ReposCreateOrUpdateFileContentsResponseConflictBasicError(BasicError)
  ReposCreateOrUpdateFileContentsResponseConflictRepositoryRuleViolationError(
    RepositoryRuleViolationError,
  )
}

pub type ReposDeleteFileRequest {
  ReposDeleteFileRequest(
    author: Option(ReposDeleteFileRequestAuthor),
    branch: Option(String),
    committer: Option(ReposDeleteFileRequestCommitter),
    message: String,
    sha: String,
  )
}

/// object containing information about the author.
pub type ReposDeleteFileRequestAuthor {
  ReposDeleteFileRequestAuthor(email: Option(String), name: Option(String))
}

/// object containing information about the committer.
pub type ReposDeleteFileRequestCommitter {
  ReposDeleteFileRequestCommitter(email: Option(String), name: Option(String))
}

pub type ReposDeleteFileResponseServiceUnavailable {
  ReposDeleteFileResponseServiceUnavailable(
    code: Option(String),
    documentation_url: Option(String),
    message: Option(String),
  )
}

pub type ReposGetContentResponseOk {
  ReposGetContentResponseOkContentDirectory(ContentDirectory)
  ReposGetContentResponseOkContentFile(ContentFile)
  ReposGetContentResponseOkContentSymlink(ContentSymlink)
  ReposGetContentResponseOkContentSubmodule(ContentSubmodule)
}

pub type RepositoryRuleViolationErrorMetadata {
  RepositoryRuleViolationErrorMetadata(
    secret_scanning: Option(RepositoryRuleViolationErrorMetadataSecretScanning),
  )
}

pub type RepositoryRuleViolationErrorMetadataSecretScanning {
  RepositoryRuleViolationErrorMetadataSecretScanning(
    bypass_placeholders: Option(
      RepositoryRuleViolationErrorMetadataSecretScanningBypassPlaceholders,
    ),
  )
}

pub type RepositoryRuleViolationErrorMetadataSecretScanningBypassPlaceholders =
  List(RepositoryRuleViolationErrorMetadataSecretScanningBypassPlaceholdersItem)

pub type RepositoryRuleViolationErrorMetadataSecretScanningBypassPlaceholdersItem {
  RepositoryRuleViolationErrorMetadataSecretScanningBypassPlaceholdersItem(
    placeholder_id: Option(SecretScanningPushProtectionBypassPlaceholderId),
    token_type: Option(String),
  )
}

pub type ValidationErrorErrors =
  List(ValidationErrorErrorsItem)

pub type ValidationErrorErrorsItem {
  ValidationErrorErrorsItem(
    code: String,
    field: Option(String),
    index: Option(Int),
    message: Option(String),
    resource: Option(String),
    value: Option(ValidationErrorErrorsItemValue),
  )
}

pub type ValidationErrorErrorsItemValue {
  ValidationErrorErrorsItemValueValidationErrorErrorsItemValueVariant0(
    ValidationErrorErrorsItemValueVariant0,
  )
  ValidationErrorErrorsItemValueValidationErrorErrorsItemValueVariant1(
    ValidationErrorErrorsItemValueVariant1,
  )
  ValidationErrorErrorsItemValueValidationErrorErrorsItemValueVariant2(
    ValidationErrorErrorsItemValueVariant2,
  )
}

pub type ValidationErrorErrorsItemValueVariant0 =
  Option(String)

pub type ValidationErrorErrorsItemValueVariant1 =
  Option(Int)

pub type ValidationErrorErrorsItemValueVariant2 =
  Option(List(String))

/// How the author is associated with the repository.
pub type AuthorAssociation {
  AuthorAssociationCOLLABORATOR
  AuthorAssociationCONTRIBUTOR
  AuthorAssociationFIRSTTIMER
  AuthorAssociationFIRSTTIMECONTRIBUTOR
  AuthorAssociationMANNEQUIN
  AuthorAssociationMEMBER
  AuthorAssociationNONE
  AuthorAssociationOWNER
}

/// Basic Error
pub type BasicError {
  BasicError(
    documentation_url: Option(String),
    message: Option(String),
    status: Option(String),
    url: Option(String),
  )
}

/// Commit
pub type Commit {
  Commit(
    author: Option(CommitAuthor),
    comments_url: String,
    commit: CommitCommit,
    committer: Option(CommitCommitter),
    files: Option(List(DiffEntry)),
    html_url: String,
    node_id: String,
    parents: CommitParents,
    sha: String,
    stats: Option(CommitStats),
    url: String,
  )
}

/// Commit Comparison
pub type CommitComparison {
  CommitComparison(
    ahead_by: Int,
    base_commit: Commit,
    behind_by: Int,
    commits: List(Commit),
    diff_url: String,
    files: Option(List(DiffEntry)),
    html_url: String,
    merge_base_commit: Commit,
    patch_url: String,
    permalink_url: String,
    status: CommitComparisonStatus,
    total_commits: Int,
    url: String,
  )
}

pub type ContentDirectory =
  List(ContentDirectoryItem)

/// Content File
pub type ContentFile {
  ContentFile(
    links: ContentFileLinks,
    content: String,
    download_url: Option(String),
    encoding: String,
    git_url: Option(String),
    html_url: Option(String),
    name: String,
    path: String,
    sha: String,
    size: Int,
    submodule_git_url: Option(String),
    target: Option(String),
    url: String,
  )
}

/// An object describing a submodule
pub type ContentSubmodule {
  ContentSubmodule(
    links: ContentSubmoduleLinks,
    download_url: Option(String),
    git_url: Option(String),
    html_url: Option(String),
    name: String,
    path: String,
    sha: String,
    size: Int,
    submodule_git_url: String,
    url: String,
  )
}

/// An object describing a symlink
pub type ContentSymlink {
  ContentSymlink(
    links: ContentSymlinkLinks,
    download_url: Option(String),
    git_url: Option(String),
    html_url: Option(String),
    name: String,
    path: String,
    sha: String,
    size: Int,
    target: String,
    url: String,
  )
}

/// Content Tree
pub type ContentTree {
  ContentTree(
    links: ContentTreeLinks,
    content: Option(String),
    download_url: Option(String),
    encoding: Option(String),
    entries: Option(ContentTreeEntries),
    git_url: Option(String),
    html_url: Option(String),
    name: String,
    path: String,
    sha: String,
    size: Int,
    type_: String,
    url: String,
  )
}

/// Diff Entry
pub type DiffEntry {
  DiffEntry(
    additions: Int,
    blob_url: String,
    changes: Int,
    contents_url: String,
    deletions: Int,
    filename: String,
    patch: Option(String),
    previous_filename: Option(String),
    raw_url: String,
    sha: Option(String),
    status: DiffEntryStatus,
  )
}

/// An object without any properties.
pub type EmptyObject {
  EmptyObject
}

/// An enterprise on GitHub.
pub type Enterprise {
  Enterprise(
    avatar_url: String,
    created_at: Option(String),
    description: Option(String),
    html_url: String,
    id: Int,
    name: String,
    node_id: String,
    slug: String,
    updated_at: Option(String),
    website_url: Option(String),
  )
}

/// File Commit
pub type FileCommit {
  FileCommit(commit: FileCommitCommit, content: Option(FileCommitContent))
}

/// Metaproperties for Git author/committer information.
pub type GitUser {
  GitUser(date: Option(String), email: Option(String), name: Option(String))
}

/// GitHub apps are a new way to extend GitHub. They can be installed directly on organizations and user accounts and granted access to specific repositories. They come with granular permissions and built-in webhooks. GitHub apps are first class actors within GitHub.
pub type Integration {
  Integration(
    client_id: Option(String),
    created_at: String,
    description: Option(String),
    events: List(String),
    external_url: String,
    html_url: String,
    id: Int,
    installations_count: Option(Int),
    name: String,
    node_id: String,
    owner: IntegrationOwner,
    permissions: IntegrationPermissions,
    slug: Option(String),
    updated_at: String,
  )
}

/// Comments provide a way for people to collaborate on an issue.
pub type IssueComment {
  IssueComment(
    author_association: Option(AuthorAssociation),
    body: Option(String),
    body_html: Option(String),
    body_text: Option(String),
    created_at: String,
    html_url: String,
    id: Int,
    issue_url: String,
    minimized: Option(IssueCommentMinimized2),
    node_id: String,
    performed_via_github_app: Option(IssueCommentPerformedViaGithubApp),
    pin: Option(IssueCommentPin),
    reactions: Option(ReactionRollup),
    updated_at: String,
    url: String,
    user: Option(IssueCommentUser),
  )
}

/// Details about why an issue comment was minimized.
pub type IssueCommentMinimized {
  IssueCommentMinimized(reason: Option(String))
}

/// Context around who pinned an issue comment and when it was pinned.
pub type PinnedIssueComment {
  PinnedIssueComment(
    pinned_at: String,
    pinned_by: Option(PinnedIssueCommentPinnedBy),
  )
}

pub type ReactionRollup {
  ReactionRollup(
    plus_1: Int,
    minus_1: Int,
    confused: Int,
    eyes: Int,
    heart: Int,
    hooray: Int,
    laugh: Int,
    rocket: Int,
    total_count: Int,
    url: String,
  )
}

/// Repository rule violation was detected
pub type RepositoryRuleViolationError {
  RepositoryRuleViolationError(
    documentation_url: Option(String),
    message: Option(String),
    metadata: Option(RepositoryRuleViolationErrorMetadata),
    status: Option(String),
  )
}

pub type SecretScanningPushProtectionBypassPlaceholderId =
  String

/// A GitHub user.
pub type SimpleUser {
  SimpleUser(
    avatar_url: String,
    email: Option(String),
    events_url: String,
    followers_url: String,
    following_url: String,
    gists_url: String,
    gravatar_id: Option(String),
    html_url: String,
    id: Int,
    login: String,
    name: Option(String),
    node_id: String,
    organizations_url: String,
    received_events_url: String,
    repos_url: String,
    site_admin: Bool,
    starred_at: Option(String),
    starred_url: String,
    subscriptions_url: String,
    type_: String,
    url: String,
    user_view_type: Option(String),
  )
}

/// Validation Error
pub type ValidationError {
  ValidationError(
    documentation_url: String,
    errors: Option(ValidationErrorErrors),
    message: String,
  )
}

pub type Verification {
  Verification(
    payload: Option(String),
    reason: String,
    signature: Option(String),
    verified: Bool,
    verified_at: Option(String),
  )
}
