name: Check DCO

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  local:
    name: Check DCO
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write # Write a comment with DCO signoff status.

    steps:
      - name: Harden the runner
        uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        with:
          egress-policy: block
          disable-sudo: true
          allowed-endpoints: >
            api.github.com:443
            github.com:443

      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 #v6.0.1
        with:
          persist-credentials: false

      - uses: ./
        with:
          config: |
            comment = true
