name: Gleam verify

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  test:
    name: Run Gleam tests
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Harden the runner
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            builds.hex.pm:443
            github.com:443
            registry.npmjs.org:443
            release-assets.githubusercontent.com:443
            repo.hex.pm:443

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - uses: erlef/setup-beam@54075bcc5e249e4758d363f27d099f55d843f124 # v1.24.1
        with:
          otp-version: "28"
          gleam-version: "1.17"
          rebar3-version: "3"

      - run: gleam deps download

      - run: gleam format --check src test

      - run: gleam build
      - run: gleam test

      - run: gleam run -m pontil_build

      - name: Ensure that nothing changed in dist (action is not ready)
        id: diff
        run: |
          if [[ "$(git diff --ignore-space-at-eol --text dist/ | wc -l)" -gt 0 ]]; then
            echo "Detected uncommitted changes after build. See status below:"
            git diff --text --ignore-space-at-eol dist/
            exit 1
          fi


